### ISSUE TITLE
Activating ADS1115: Analog pH/EC causes Error 500

### ISSUE THREAD

**Issue by dookaloosy** [kizniche/Mycodo#1004]
### Describe the problem/bug

Activating ADS1115: Analog pH/EC causes Error 500, on a fresh install of Mycodo 8.10.1 that has been upgraded to master as of 5/15/2021 4pm PT (it should have incorporated commit #ef88fd9).

```
Error 500: Internal Server Error
Something bad happened but it's probably not your fault. Letting the developers know about these issues is crucial to supporting Mycodo. Please submit a new issue on GitHub with the following diagnostic information and error traceback (copy the entire traceback):

Mycodo: 8.10.1

Alembic: d46e17d65f48

Model: Raspberry Pi 3 Model B Rev 1.2

Release:
Distributor ID: Raspbian
Description: Raspbian GNU/Linux 10 (buster)
Release: 10
Codename: buster

Firmware:
Feb 25 2021 12:12:09
Copyright (c) 2012 Broadcom
version 564e5f9b852b23a330b1764bcf0b2d022a20afd0 (clean) (release) (start)

Error (Full Traceback):

Traceback (most recent call last):
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask_restx/api.py", line 652, in error_router
    return original_handler(e)
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/pi/Mycodo/mycodo/mycodo_flask/routes_page.py", line 1951, in page_input
    utils_input.input_activate(form_mod_input)
  File "/home/pi/Mycodo/mycodo/mycodo_flask/utils/utils_input.py", line 666, in input_activate
    if each_option['id'] not in custom_options_values_inputs[input_dev.unique_id]:
KeyError: 'id'
```

### Versions:

 - Mycodo Version: 8.10.1+
 - Raspberry Pi Version: 3B
 - Raspbian OS Version: Linux raspberrypi 5.10.17-v7+ #1403 SMP Mon Feb 22 11:29:51 GMT 2021 armv7l GNU/Linux

### Reproducibility

1. Fresh install of Mycodo 8.10.1
2. Upgrade to master
3. Add ADS1115: Analog pH/EC
4. Activate and run into error

### Expected behavior

Activation should have no errors.

### Screenshots

N/A

### Additional context

N/A

**Comment by kizniche** [comment]
Thanks for the bug report. Just committed a fix.
