### ISSUE TITLE
SSD1306 OLED will not work

### ISSUE THREAD

**Issue by dexilimes** [kizniche/Mycodo#1007]
Hi there,
After I recently upgraded to 8.10.1 my OLED screen has stopped working. 

I added the LCD in the new section in the functions menu, but when I activate the LCD it comes up with the following error:

2021-05-18 22:48:27,710 - DEBUG - mycodo.function.display_ssd1306_oled_128x64_i2c_68f19684 - Line sets: [[0, 1, 2, 3, 4, 5, 6, 7]]
2021-05-18 22:48:27,710 - ERROR - mycodo.function.display_ssd1306_oled_128x64_i2c_68f19684 - Starting LCD Function
Traceback (most recent call last):
  File "/home/pi/Mycodo/mycodo/functions/display_ssd1306_oled_128x64_i2c.py", line 358, in initialize_variables
    self.device = LCD_Pioled_Circuitpython(lcd_settings_dict=lcd_settings_dict)
  File "/var/mycodo-root/mycodo/devices/lcd_pioled_circuitpython.py", line 42, in __init__
    self.spi_bus = lcd_settings_dict["spi_bus"]
KeyError: 'spi_bus'
2021-05-18 22:48:27,711 - INFO - mycodo.controllers.controller_function_68f19684 - Activated in 111.0 ms
2021-05-18 22:48:27,711 - ERROR - mycodo.function.display_ssd1306_oled_128x64_i2c_68f19684 - LCD not set up

**Comment by kizniche** [comment]
Hi. Thanks for the bug report. We've been figuring this issue out over on the forum at https://forum.kylegabriel.com/t/ssd1306-display-functions-no-longer-work/160/16

**Comment by dexilimes** [comment]
I upgraded to the Master and it worked! 

thanks again!
