### ISSUE TITLE
Error 500 When Attempting to Calibrate Atlas PH Sensor

### ISSUE THREAD

**Issue by ckgarside** [kizniche/Mycodo#1022]
### Describe the problem/bug

After entering water temperature and pressing continue button, page displays Error 500

### Versions:

Version: 8.11.0
Database: 43c72773dbe8
Model: Raspberry Pi 3 Model B Rev 1.2

### Reproducibility

Please list specific setup details that are involved and the steps to reproduce the behavior:

1. Setup
2. Calibration and Setup
3. Atlas Scientific pH Sensor
4. Select 3 point calibration
5. Begin calibration
6. Enter Temperature
7. Press continue
8. Error 500

### Screenshots

N/A

### Additional context

Version: 8.11.0
Database: 43c72773dbe8
Model: Raspberry Pi 3 Model B Rev 1.2

Release:
Distributor ID: Raspbian
Description: Raspbian GNU/Linux 10 (buster)
Release: 10
Codename: buster

Firmware:
Aug 19 2020 17:40:15
Copyright (c) 2012 Broadcom
version e90cba19a98a0d1f2ef086b9cafcbca00778f094 (clean) (release) (start)

Error (Full Traceback):

Traceback (most recent call last):
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask_restx/api.py", line 652, in error_router
    return original_handler(e)
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/pi/Mycodo/mycodo/mycodo_flask/routes_calibration.py", line 515, in setup_atlas_ph
    current_stage='temperature', next_stage=next_stage)
  File "/home/pi/Mycodo/mycodo/mycodo_flask/routes_calibration.py", line 710, in dual_commands_to_sensor
    first_cmd, set_amount=set_amount)
  File "/home/pi/Mycodo/mycodo/utils/atlas_calibration.py", line 103, in calibrate
    err, msg = self.send_command('T,{:.2f}'.format(set_amount))
ValueError: Unknown format code 'f' for object of type 'str'

**Comment by ckgarside** [comment]
> Try calibrating from the Input itself. I'll soon be completely removing the Calibration page in favor of calibration from the Input module.

Understood. Will be doing that method in the future. 

Thanks for the assistance!
