### ISSUE TITLE
Live measurements and jauge widgets error

### ISSUE THREAD

**Issue by pe2269** [kizniche/Mycodo#1063]
Hi Kizniche,

I am using Mycodo system in order to monitor temperature and hmidity at home with a raspberry 4.
I have a DHT22 and 3 Xiaomi Mija (bluetooth temperature & hum).
All worked fine when suddenly yesterday  the live measurement webpage show the error below.
(Measurements are still working, i can see it thanks to the Asynchronous Graphs but the live measurement page and my jauges widgets dashboard are down too).

thank you for all your work you share with us !
[](![Jauge_dashboard](https://user-images.githubusercontent.com/85128895/127764568-0af9e892-cbeb-473c-add4-e5aacf2c6214.JPG))

Version: 8.11.0
Database: bdc03b708ac6
Model: Raspberry Pi 3 Model B Plus Rev 1.3

Release:
Distributor ID: Raspbian
Description: Raspbian GNU/Linux 10 (buster)
Release: 10
Codename: buster

Firmware:
May 27 2021 14:05:31
Copyright (c) 2012 Broadcom
version 7d9a298cda813f747b51fe17e1e417e7bf5ca94d (clean) (release) (start_x)

Error (Full Traceback):

Traceback (most recent call last):
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask_restx/api.py", line 652, in error_router
    return original_handler(e)
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/pi/Mycodo/mycodo/mycodo_flask/routes_page.py", line 942, in page_live
    use_unit=use_unit)
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/pi/Mycodo/mycodo/mycodo_flask/templates/pages/live.html", line 3, in top-level template code
    {% set help_page = ["https://kizniche.github.io/Mycodo/Data-Viewing/#live-measurements", _('Live Measurements')] %}
  File "/home/pi/Mycodo/mycodo/mycodo_flask/templates/layout.html", line 384, in top-level template code
    {%- block body %}{% endblock -%}
  File "/home/pi/Mycodo/mycodo/mycodo_flask/templates/pages/live.html", line 162, in block 'body'
    {%- if dict_units[dict_measure_units[each_meas.unique_id]]['unit'] -%}
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/jinja2/environment.py", line 455, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'collections.OrderedDict object' has no attribute ''

**Comment by pe2269** [comment]
It was an inactive function which cause the problem. I delete them all and all is fix now.
