### ISSUE TITLE
8.12.5 Dependencies page internal server error

### ISSUE THREAD

**Issue by Ikzy** [kizniche/Mycodo#1082]
### Describe the problem/bug
When opening options and the dependencies page (mycodo/admin/dependencies/) page takes 20 seconds to load and throws an internal server error (500) *see other context

### Versions:

 - Mycodo Version: *[8.12.5]*
 - Raspberry Pi Version: *[4]*
 - Raspbian OS Version: *[ Buster]*

### Reproducibility

Please list specific setup details that are involved and the steps to reproduce the behavior:

1. *[Go to options]*
2. *[Click on dependencies]*
3.  PROFIT

### Additional context
Full Traceback:

**
Error 500: Internal Server Error

Something bad happened but it's probably not your fault. Letting the developers know about these issues is crucial to supporting Mycodo. Please submit a new issue on GitHub with the following diagnostic information and error traceback (copy the entire traceback):

Version: 8.12.5 
Database: 6e394f2e8fec 
Model: Raspberry Pi 4 Model B Rev 1.2

Release:
Distributor ID: Raspbian
Description: Raspbian GNU/Linux 10 (buster)
Release: 10
Codename: buster

Firmware:
Apr 30 2021 13:46:42 
Copyright (c) 2012 Broadcom
version d7f29d96450abfc77cd6cf011af1faf1e03e5e56 (clean) (release) (start_x)

Error (Full Traceback):

Traceback (most recent call last):
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask_restx/api.py", line 652, in error_router
    return original_handler(e)
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/pi/Mycodo/mycodo/mycodo_flask/routes_admin.py", line 379, in admin_dependencies
    if each_dep not in unmet_list:
TypeError: unhashable type: 'list'
**

**Comment by kizniche** [comment]
This issue has been mentioned on **DIY Automation Forum**. There might be relevant details there:

https://forum.kylegabriel.com/t/reinstalling-an-unmet-dependency/351/1

**Comment by zachwoodill** [comment]
Hi @kizniche I just wanted to mention I am having the same issue.

**Comment by kizniche** [comment]
@zachwoodill This has been fixed and will be in the next release.
