### ISSUE TITLE
v8.12.8 Unable to calibrate Atlas probes, pH and TDS.

### ISSUE THREAD

**Issue by joeschmit** [kizniche/Mycodo#1116]
Running v8.12.8 Unable to calibrate Atlas probes, pH and TDS. Its also not totally clear on procedure. Here is what I am doing with no success:

1. Setup, Inputs, Select Input, Atlas Scientific, Atlas pH In Concentration, I2C
2. Activate input
3. Input Settings, set temp comp (2021-11-24 11:25:09,290 - INFO - mycodo.inputs.atlas_ph_249bcffa - Command returned: None)
4. Clear cal, 2021-11-24 11:25:49,673 - INFO - mycodo.inputs.atlas_ph_249bcffa - Device Calibrated?: None
5. Calibrate mid, 2021-11-24 11:26:16,227 - ERROR - mycodo.controllers.controller_input_a9b8e19c - loop() Error
Traceback (most recent call last):.
6. Calibrate low, high etc same results.
7. Close
8. Deactivate input
9. Open
10. Save, 2021-11-24 11:39:06,211 - ERROR - mycodo.inputs.atlas_pt1000_a9b8e19c - Cannot set a value of None. Must be a float or string representing a float. Check the sensor and Input module is working correctly.
11. Close
12. Activate input

I get an attribute error in the logs each time I attempt to calibrate. When I enter values and attempt to save they are not appended to database and go back to defaults.

Other notes: probes are showing measurement data, which looks close to what they should be, so that should confirm my sensors are in fact reading, adding data to db. 

Mycodo Version: 8.12.8 
Python Version: 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0] 
Database Version: 0187ea22dc4b
Daemon Status: Running 
Daemon Process ID: 952 
Daemon RAM Usage: 53.744 MB 
Daemon Virtualenv: Yes 
Frontend Process ID: 506 
Frontend RAM Usage: 64.388 MB 
Frontend Virtualenv: Yes

....2021-11-24 11:16:26,275 - ERROR - mycodo.controllers.controller_input_a9b8e19c - loop() Error
Traceback (most recent call last):
  File "/var/mycodo-root/mycodo/controllers/base_controller.py", line 86, in run
    self.loop()
  File "/var/mycodo-root/mycodo/controllers/controller_input.py", line 230, in loop
    self.create_measurements_dict(),
  File "/var/mycodo-root/mycodo/controllers/controller_input.py", line 403, in create_measurements_dict
    each_measurement)
  File "/var/mycodo-root/mycodo/utils/influx.py", line 195, in parse_measurement
    measurements_record[each_channel]['value'])
  File "/var/mycodo-root/mycodo/inputs/sensorutils.py", line 42, in convert_units
    replaced_str = conversion.equation.replace('x', str(measure_value))
AttributeError: 'NoneType' object has no attribute 'equation'
2021-11-24 11:16:36,225 - ERROR - mycodo.controllers.controller_input_a9b8e19c - loop() Error
Traceback (most recent call last):
  File "/var/mycodo-root/mycodo/controllers/base_controller.py", line 86, in run
    self.loop()
  File "/var/mycodo-root/mycodo/controllers/controller_input.py", line 230, in loop
    self.create_measurements_dict(),
  File "/var/mycodo-root/mycodo/controllers/controller_input.py", line 403, in create_measurements_dict
    each_measurement)
  File "/var/mycodo-root/mycodo/utils/influx.py", line 195, in parse_measurement
    measurements_record[each_channel]['value'])
  File "/var/mycodo-root/mycodo/inputs/sensorutils.py", line 42, in convert_units
    replaced_str = conversion.equation.replace('x', str(measure_value))
AttributeError: 'NoneType' object has no attribute 'equation'

**Comment by kizniche** [comment]
Please provide information about your Input settings, preferably a screenshot.
