### ISSUE TITLE
error creating widget

### ISSUE THREAD

**Issue by Bananachaos** [kizniche/Mycodo#1118]
Traceback (most recent call last):
  File "/home/pi/Mycodo/env/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/Mycodo/env/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/Mycodo/env/lib/python3.9/site-packages/flask_restx/api.py", line 672, in error_router
    return original_handler(e)
  File "/home/pi/Mycodo/env/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/Mycodo/env/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/pi/Mycodo/env/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/pi/Mycodo/mycodo/mycodo_flask/routes_dashboard.py", line 145, in page_dashboard
    unmet_dependencies = utils_dashboard.widget_add(form_base, request.form)
  File "/home/pi/Mycodo/mycodo/mycodo_flask/utils/utils_dashboard.py", line 230, in widget_add
    error, new_widget = dict_widgets[widget_name]['execute_at_creation'](
  File "/home/pi/Mycodo/mycodo/widgets/widget_gauge_solid.py", line 51, in execute_at_creation
    color = color_list[i + 1]
IndexError: list index out of range

### Describe the problem/bug

I was attempting to make an angular graph widget on my phone specific dashboard to map my ppm and it simply crashed on me and showed me a screen recommending i post it here.  

### Versions:

 - Mycodo Version: 18.12.8
 - Raspberry Pi Version: 4+ 2gb
 - Raspbian OS Version: Bullseye

### Reproducibility

Please list specific setup details that are involved and the steps to reproduce the behavior:

1. open mycodo ip on phone
2. go to dash
3. choose angular gauge widget
4. chose ppm, clicked create
5. it crashed

### Expected behavior

An angular graph of my ppm simply

### Screenshots

*[If applicable, add screenshots to help explain your problem - replace this with your own text]*

### Additional context

*[Anything that should be added to make it easier to address this issue - replace this with your own text]

**Comment by kizniche** [comment]
I was not able to replicate this issue. Are you using any special characters in your input name? Is your set language English? A new version was just released- upgrade and see if the issue persists.
