### ISSUE TITLE
exceptions thrown in regulate_ph_ec.py

### ISSUE THREAD

**Issue by cperricos** [kizniche/Mycodo#1255]
Hello,
I am trying to use the "Regulate PH and EC" function from your library to regulate PH and ORb in my pool system (I think the function is amaing and just what i need). I can get it to work with my Ezo pump however. I have tried parameter that will actvate the pmp, but the code causes excpetions here is the log:

2023-01-02 09:28:34,517 - INFO - mycodo.controllers.controller_function_dfc57aca - Activated in 1723.7 ms
2023-01-02 09:28:44,198 - DEBUG - mycodo.function.regulate_ph_ec_dfc57aca - Most recent timestamp and measurement for pH: 2023-01-02T09:28:36.426246Z, 7.074249999999999
2023-01-02 09:28:44,575 - DEBUG - mycodo.function.regulate_ph_ec_dfc57aca - Most recent timestamp and measurement for EC: 2023-01-02T09:28:26.837841Z, 840.3833333333332
2023-01-02 09:28:44,583 - DEBUG - mycodo.function.regulate_ph_ec_dfc57aca - pH is dangerously high: 7.07. Should be < 7.00. Dispensing 2.0 sec acid
2023-01-02 09:28:44,590 - ERROR - mycodo.controllers.controller_function_dfc57aca - Exception while running loop()
Traceback (most recent call last):
  File "/var/mycodo-root/mycodo/controllers/controller_function.py", line 76, in loop
    self.run_function.loop()
  File "/home/pi/Mycodo/mycodo/functions/custom_functions/regulate_ph_ec.py", line 806, in loop
    "sec_ph_lower", self.get_custom_option("sec_ph_lower") + self.output_ph_amount)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'

any suggestions?

many thanks

**Comment by cperricos** [comment]
Apologies - will get the latest code   
  
  
  
  
  
  
  

  
  
>

**Comment by kizniche** [comment]
No problem. If you still have issues after you try the code on github, let us know here what errors you get.

**Comment by cperricos** [comment]
I think I have managed to get it to work now.
  
Am exception is thrown when the timers and summation volumes aren’t reset at the beginning of the function. From what I can tell but otherwise it’s great.
  
One additional question I had is how can the timer and summation variables be accessed from outside the function?
  

  
For example, if we are summing    up the total amount of acid (Ph-) dispensed and we know the overall acid container volume you could keep track of how much acid is left in the container and send an alert when a new container needs to be ordered. Is it    possible To expose the summation measurements so they can be used in other functions or shown on a dashboard?
  

  
Thanks   
  

  

  
  
  
  
  
  
  

  
  
>

**Comment by kizniche** [comment]
>exception is thrown

What is the error?
