### ISSUE TITLE
Python 3 support attempt

### ISSUE THREAD

**Issue by kizniche** [kizniche/Mycodo#253]
I decided to make an attempt at getting Mycodo running with Python 3 (3.4) in a [python3 branch](https://github.com/kizniche/Mycodo/tree/python3_merge).

After installing Mycodo normally, as it's done with python 2.7, I began assessing the extent of [what changes were necessary](https://github.com/kizniche/Mycodo/tree/python3#python-3-branch-progress) to get the daemon running.

New commands were added to install python3 and python3-dev,

```sudo /bin/bash ~/Mycodo/mycodo/scripts/upgrade_commands.sh update-packages```

create a python 3 virtual environment,

```sudo /bin/bash ~/Mycodo/mycodo/scripts/upgrade_commands.sh setup-virtualenv-py3```

and update the python 3 pip packages

```sudo /bin/bash ~/Mycodo/mycodo/scripts/upgrade_commands.sh update-pip-packages-py3```

After disabling/replacing some modules, mycodo_daemon.py ran to a certain point, then crashed without throwing an exception. I narrowed it down to [db_retrieve_table_daemon()](https://github.com/kizniche/Mycodo/blob/376636cc18f77b13904f1129c3dfe039e81038c8/mycodo/mycodo_daemon.py#L653), which I was able to follow to [here](https://github.com/kizniche/Mycodo/blob/376636cc18f77b13904f1129c3dfe039e81038c8/mycodo/utils/database.py#L65).

It's interesting that a previous call to this function ([here](https://github.com/kizniche/Mycodo/blob/376636cc18f77b13904f1129c3dfe039e81038c8/mycodo/mycodo_daemon.py#L283), [here](https://github.com/kizniche/Mycodo/blob/376636cc18f77b13904f1129c3dfe039e81038c8/mycodo/mycodo_daemon.py#L513-L514)) isn't an issue. This can be seen when attempting to start the daemon with a few log lines added.

```
sudo ~/Mycodo/env_py3/bin/python3 ~/Mycodo/mycodo/mycodo_daemon.py -d
```

Log output:

```
2017-06-04 20:41:49,465 - mycodo - INFO - Mycodo daemon v5.0.32 starting
2017-06-04 20:41:49,465 - mycodo - DEBUG - Refreshing camera settings
2017-06-04 20:41:49,466 - mycodo.database - ERROR - TEST05
2017-06-04 20:41:49,509 - mycodo.database - ERROR - TEST06
2017-06-04 20:41:49,509 - mycodo.database - ERROR - TEST07
2017-06-04 20:41:49,671 - mycodo.database - ERROR - TEST08
2017-06-04 20:41:49,672 - mycodo.database - ERROR - TEST10
2017-06-04 20:41:49,730 - mycodo.database - ERROR - TEST11
2017-06-04 20:41:49,731 - mycodo.database - ERROR - TEST12
2017-06-04 20:41:49,735 - mycodo.database - ERROR - TEST15
2017-06-04 20:41:49,736 - mycodo - DEBUG - Refreshing misc settings
2017-06-04 20:41:49,737 - mycodo.database - ERROR - TEST05
2017-06-04 20:41:49,748 - mycodo.database - ERROR - TEST06
2017-06-04 20:41:49,749 - mycodo.database - ERROR - TEST07
2017-06-04 20:41:49,751 - mycodo.database - ERROR - TEST08
2017-06-04 20:41:49,751 - mycodo.database - ERROR - TEST09
2017-06-04 20:41:49,791 - mycodo.database - ERROR - TEST11
2017-06-04 20:41:49,792 - mycodo.database - ERROR - TEST12
2017-06-04 20:41:49,796 - mycodo.database - ERROR - TEST15
2017-06-04 20:41:49,798 - mycodo - INFO - Anonymous statistics enabled
2017-06-04 20:41:51,522 - mycodo - ERROR - TEST01
2017-06-04 20:41:51,523 - mycodo - ERROR - TEST03
2017-06-04 20:41:51,524 - mycodo.database - ERROR - TEST05
2017-06-04 20:41:51,544 - mycodo.database - ERROR - TEST06
2017-06-04 20:41:51,544 - mycodo.database - ERROR - TEST07
2017-06-04 20:41:51,547 - mycodo.database - ERROR - TEST08
2017-06-04 20:41:51,548 - mycodo.database - ERROR - TEST10
```

I'm starting this issue to document my progress. Any comments or suggestions are welcome.

**Comment by kizniche** [comment]
Notice I added [a line](https://github.com/kizniche/Mycodo/blob/python3/mycodo/databases/models/lcd.py#L8) to all database classes to resolve an issue with sqlalchemy.

```python
    __table_args__ = {'extend_existing': True}
```

However, I'm not sure if this the correct way to fix the sqlalchemy issue or if this is related to the original issue.

**Comment by kizniche** [comment]
I'm resuming this effort today for a few hours to see if I can get the backend and frontend working.

**Comment by kizniche** [comment]
I made more progress than last time getting Mycodo running with Python 3.4. I managed to get the backend running, though I haven't extensively tested everything.

I'm now having difficulty with the Flask frontend. I'm currently hung up on getting Flask to start. Specifically, I'm stuck on an error during startup where there's a query to the database to retrieve the columns of the Roles table to discover the available user roles.

In order to run the [python3_merge](https://github.com/kizniche/Mycodo/tree/python3_merge) branch, first check it out, then set up the python3 virtualenv and update the pip3 packages with these commands:

```bash
sudo /bin/bash ./mycodo/scripts/upgrade_commands.sh setup-virtualenv-python3
sudo /bin/bash ./mycodo/scripts/upgrade_commands.sh update-pip-packages-py3
```

The daemon runs fine now, and can be started with:

```
sudo ./env_py3/bin/python3 ./mycodo/mycodo_daemon.py
```

The Flask web server, however, when started with the following command:

```
sudo ./env_py3/bin/python3 ./mycodo/start_flask_ui.py -d
```

Returns the following error and quits:

```
kiz@tnccave:~/Mycodo $ sudo ./env_py3/bin/python3 ./mycodo/start_flask_ui.py -d
Traceback (most recent call last):
  File "./mycodo/start_flask_ui.py", line 11, in <module>
    app = create_app()  # required by the wsgi config and main()
  File "/home/kiz/Mycodo/mycodo/mycodo_flask/app.py", line 70, in create_app
    register_extensions(app)
  File "/home/kiz/Mycodo/mycodo/mycodo_flask/app.py", line 114, in register_extensions
    populate_db()
  File "/home/kiz/Mycodo/mycodo/databases/models/__init__.py", line 123, in populate_db
    known_roles = {r.name: r for r in Role.query.all()}
AttributeError: 'NoneType' object has no attribute 'all'
```

@etiology, I know you were a huge influence in getting this part of Mycodo up and running. If you or anyone else is familiar with this issue, could you please point me in the correct direction to figuring this out? I'm not extremely familiar with how sqlalchemy was implemented here in Flask, so I feel like I'm all thumbs trying to fix this to work with Python 3. Thanks in advance if anyone can lend their expertise.

**Comment by kizniche** [comment]
I found it was my fault for the error. I removed the following lines from [user.py](https://github.com/kizniche/Mycodo/blob/cca9f4682f5e7b004c375fec6ca9ca6c580d2d27/mycodo/databases/models/user.py#L12) and [role.py](https://github.com/kizniche/Mycodo/blob/cca9f4682f5e7b004c375fec6ca9ca6c580d2d27/mycodo/databases/models/role.py#L9) that i had added to get the daemon to run, and Flask now runs with Python 3.

```python
__abstract__ = True
```

However, now the daemon won't run without throwing this error:

```
2017-12-17 23:21:13,480 - mycodo.daemon - ERROR - Could not start all controllers: One or more mappers failed to initialize - can't proceed with initializati
on of other mappers. Triggering mapper: 'Mapper|User|users'. Original exception was: Multiple classes found for path "Role" in the registry of this declarati
ve base. Please use a fully module-qualified path.
Traceback (most recent call last):
  File "./mycodo/mycodo_daemon.py", line 778, in start_all_controllers
    'Timer': db_retrieve_table_daemon(Timer, entry='all'),
  File "/home/kiz/Mycodo/mycodo/utils/database.py", line 58, in db_retrieve_table_daemon
    return_table = new_session.query(table)
  File "/home/kiz/Mycodo/env_py3/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 1393, in query
    return self._query_cls(entities, self, **kwargs)
  File "/home/kiz/Mycodo/env_py3/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 140, in __init__
    self._set_entities(entities)
  File "/home/kiz/Mycodo/env_py3/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 151, in _set_entities
    self._set_entity_selectables(self._entities)
  File "/home/kiz/Mycodo/env_py3/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 181, in _set_entity_selectables
    ent.setup_entity(*d[entity])
  File "/home/kiz/Mycodo/env_py3/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 3616, in setup_entity
    self._with_polymorphic = ext_info.with_polymorphic_mappers
  File "/home/kiz/Mycodo/env_py3/lib/python3.4/site-packages/sqlalchemy/util/langhelpers.py", line 767, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
File "/home/kiz/Mycodo/env_py3/lib/python3.4/site-packages/sqlalchemy/orm/mapper.py", line 1993, in _with_polymorphic_mappers
    configure_mappers()
File "/home/kiz/Mycodo/env_py3/lib/python3.4/site-packages/sqlalchemy/orm/mapper.py", line 3016, in configure_mappers
    raise e
sqlalchemy.exc.InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper|User|users'. Original exception was: Multiple classes found for path "Role" in the registry of this declarative base. Please use a fully module-qualified path.
```

**Comment by kizniche** [comment]
Disabling the following lines in [user.py](https://github.com/kizniche/Mycodo/blob/cca9f4682f5e7b004c375fec6ca9ca6c580d2d27/mycodo/databases/models/user.py) and [role.py](https://github.com/kizniche/Mycodo/blob/cca9f4682f5e7b004c375fec6ca9ca6c580d2d27/mycodo/databases/models/role.py) has prevented the errors. I have not been able to determine the exact reason for the issue, but I'm working around it for now until I learn more.

```python
user = db.relationship("User", back_populates="roles")
```

```python
roles = db.relationship("Role", back_populates="user")
```

**Comment by kizniche** [comment]
The python3_merge branch has just been merged into master. OpenCV was the only casualty by moving from Python 2.9 to 3.4.
