### ISSUE TITLE
SHT10 error

### ISSUE THREAD

**Issue by gadem35** [kizniche/Mycodo#282]
hi i cant run sht10 pls help me

```
2017-08-09 03:37:32,127 - mycodo.sensors.sht1x_7x - ERROR - SHT1x7xSensor raised an exception when taking a reading: Command ACK failed on step-2
Traceback (most recent call last):
  File "/var/www/mycodo/mycodo/sensors/sht1x_7x.py", line 111, in read
    self._temperature) = self.get_measurement()
  File "/var/www/mycodo/mycodo/sensors/sht1x_7x.py", line 96, in get_measurement
    temperature = sht_sensor.read_t()
  File "/var/www/mycodo/env/local/lib/python2.7/site-packages/sht_sensor/sensor.py", line 300, in read_t
    t_raw = self._get_meas_result(self.cmd.t)
  File "/var/www/mycodo/env/local/lib/python2.7/site-packages/sht_sensor/sensor.py", line 240, in _get_meas_result
    self._send(cmd)
  File "/var/www/mycodo/env/local/lib/python2.7/site-packages/sht_sensor/sensor.py", line 203, in _send
    raise ShtCommFailure('Command ACK failed on step-2')
ShtCommFailure: Command ACK failed on step-2
```

**Comment by kizniche** [comment]
What version Mycodo? Has any code been able to return a measurement, to indicate you have the sensor connected properly?
