### ISSUE TITLE
Creating gauge causes Error 500

### ISSUE THREAD

**Issue by pewi81** [kizniche/Mycodo#333]
## Mycodo Issue Report:
  - Specific Mycodo Version: 

5.4.8 (fresh install)

#### Problem Description
Please list:

  - what were you trying to do

Create gauge (angular and solid, different sizes)

  - specific setup details that are involved
 
### Errors
  - List any errors you encountered.
  - Copy and pasting crash logs, or link to any specific
code lines you've isolated (please use GitHub permalinks for this)

```
Error 500: Internal Server Error

Something bad happened but it's probably not your fault. Letting the developers know about these issues is crucial to supporting Mycodo. Please submit a new issue on GitHub with the following error traceback (copy the entire traceback):

Error (Full Traceback):

Traceback (most recent call last):
  File "/var/www/mycodo/env/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/mycodo/env/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/mycodo/env/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/mycodo/env/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/mycodo/env/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/mycodo/env/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/var/www/mycodo/mycodo/mycodo_flask/page_routes.py", line 351, in page_graph
    utils_graph.graph_add(form_add_graph, display_order)
  File "/var/www/mycodo/mycodo/mycodo_flask/utils/utils_graph.py", line 88, in graph_add
    new_graph.max_measure_age = form_add_graph.max_measure_age.data
AttributeError: 'GraphAdd' object has no attribute 'max_measure_age'

```

### Steps to Reproduce the issue:
How can this issue be reproduced?
 1. step 1
Try to create gauge
 2. step 2...
 3. etc
 
### Additional Notes
Is there anything that should be added to make it easier
to address this issue?

**Comment by kizniche** [comment]
v5.4.9 released with a fix for this issue. Thanks!
