### ISSUE TITLE
rpyc error on reboot

### ISSUE THREAD

**Issue by zsole2** [kizniche/Mycodo#410]
## Mycodo Issue Report:
  - 5.5.21
 
#### Problem Description
I got this error recenrly a few times:
```
2018-02-21 08:45:33,629 - mycodo.daemon - INFO - Mycodo terminated in 5.166 seconds


2018-02-21 08:45:34,045 - mycodo.rpyc - ERROR - client connection terminated abruptly
Traceback (most recent call last):
  File "/var/mycodo-root/env/lib/python3.5/site-packages/rpyc/utils/server.py", line 179, in _authenticate_and_serve_client
    self._serve_client(sock2, credentials)
  File "/var/mycodo-root/env/lib/python3.5/site-packages/rpyc/utils/server.py", line 203, in _serve_client
    self._handle_connection(conn)
  File "/var/mycodo-root/env/lib/python3.5/site-packages/rpyc/utils/server.py", line 209, in _handle_connection
    conn.serve_all()
  File "/var/mycodo-root/env/lib/python3.5/site-packages/rpyc/core/protocol.py", line 449, in serve_all
    self.serve(None)
  File "/var/mycodo-root/env/lib/python3.5/site-packages/rpyc/core/protocol.py", line 442, in serve
    return self.sync_recv_and_dispatch(timeout, wait_for_lock=True)
  File "/var/mycodo-root/env/lib/python3.5/site-packages/rpyc/core/protocol.py", line 417, in sync_recv_and_dispatch
    self._dispatch(data)
  File "/var/mycodo-root/env/lib/python3.5/site-packages/rpyc/core/protocol.py", line 407, in _dispatch
    raise ValueError("invalid message type: %r" % (msg,))
ValueError: invalid message type: None
2018-02-21 08:47:43,190 - mycodo.daemon - INFO - Mycodo daemon v5.5.22 starting
```
It does not affect anything operational, though.

**Comment by kizniche** [comment]
That's actually an error on shutdown. Sometimes the daemon shuts down quickly and drops the rpyc connection. I've been trying to figure out how to gracefully, but non-blocking, end the connection. Don't worry, the daemon has already properly shut down all components by this point.
