### ISSUE TITLE
6.1.0: Daily timepoint broken?

### ISSUE THREAD

**Issue by fry42** [kizniche/Mycodo#472]
Hi,

So, I've got some serous issues going on:
All my timepoint functions stopped working.

The last change I can remember before it happening was that I changed a (inverted) PWM value in a daily duration funktion to 100 (which equals 0).

The only error in the logs I could find was this one:
2018-05-13 09:27:57,264 - mycodo.daemon - ERROR - Could not turn output on: unorderable types: str() > int()
Traceback (most recent call last):
  File "/var/mycodo-root/mycodo/mycodo_daemon.py", line 780, in output_on
    trigger_conditionals=trigger_conditionals)
  File "/var/mycodo-root/mycodo/controller_output.py", line 479, in output_on_off
    duty_cycle=duty_cycle)
  File "/var/mycodo-root/mycodo/controller_output.py", line 587, in check_conditionals
    if self.is_on(output_id) and on_duration > 0:
TypeError: unorderable types: str() > int()
2018-05-13 09:28:16,603 - mycodo.daemon - ERROR - Could not turn output on: unorderable types: str() > int()
Traceback (most recent call last):
  File "/var/mycodo-root/mycodo/mycodo_daemon.py", line 780, in output_on
    trigger_conditionals=trigger_conditionals)
  File "/var/mycodo-root/mycodo/controller_output.py", line 479, in output_on_off
    duty_cycle=duty_cycle)
  File "/var/mycodo-root/mycodo/controller_output.py", line 587, in check_conditionals
    if self.is_on(output_id) and on_duration > 0:
TypeError: unorderable types: str() > int()

Right now it's hard to replicate the issue - I've got a (partly) running system and would need to completely clone it for testing. And since I'm also affected by #470 I can't change the time settings to test it.

**Comment by kizniche** [comment]
I haven't been able to replicate this issue. I'm going to release v6.1.1 soon that fixes #470. If you could test some more to figure out exactly what part of Mycodo is causing this, I can try to figure it out. Currently, there are a lot of parts that can call ```output_on()``` that the first part of your traceback references.
