### ISSUE TITLE
PWM control receiving error in log

### ISSUE THREAD

**Issue by mrplow** [kizniche/Mycodo#485]
## Mycodo Issue Report:
  - Specific Mycodo Version: 6.1.2
 
#### Problem Description
PWM control receiving error in log

  - I'm trying to control an externally powered 4pin 12V CPU fan via PWM control. Eventually I'll set it up to control temperature (but I haven't set that part up yet)
  - bcm pin: 5, library: any pin, frequency 20000 hz.
  - fan is plugged into an acdc 12v adapter and is running, control pin is connected to bcm pin 5.

### Errors
When I set a duty cycle and press Turn on I receive the following error
```
 2018-05-24 21:51:39,681 - mycodo.daemon - ERROR - Could not turn output on: unorderable types: str() > int()
Traceback (most recent call last):
  File "/var/mycodo-root/mycodo/mycodo_daemon.py", line 780, in output_on
    trigger_conditionals=trigger_conditionals)
  File "/var/mycodo-root/mycodo/controller_output.py", line 479, in output_on_off
    duty_cycle=duty_cycle)
  File "/var/mycodo-root/mycodo/controller_output.py", line 587, in check_conditionals
    if self.is_on(output_id) and on_duration > 0:
TypeError: unorderable types: str() > int()
```

### Additional Notes
I tested this exact same setup a while ago. I've log since trashed that install after upgrading my pi. I may have been 5.7 or an early version 6 mycodo. I didn't have the sensors installed so I haven't played with setting up a controller yet.

**Comment by mrplow** [comment]
Turns out my ground between the pi and the fan has become disconnected.

This fixed the actual issue of the fan speed not changing but I still receive the error.

So really this issue is just cosmetic. Although I assume that error output could lead to sanitizing some code.
I looked but I'm not well versed enough in Python to correct it.
