### ISSUE TITLE
CCS811 Problem

### ISSUE THREAD

**Issue by pmunz75** [kizniche/Mycodo#503]
Specific Mycodo Version: 6.1.4
    Raspberry PI 3B+
    16 GB SD Card Class10
    System : Linux mycodo 4.14.52-v7+ #1123 SMP Wed Jun 27 17:35:49 BST 2018 armv7l GNU/Linux
    Power 5v 2.0 Amp
    Sensor : BME280 ( 3 meters ) , DS18B20 , Original Atlas PH i2c, CCS811 , BH1750

I've already tried everything.
solder tested.
The css811 not Run 

sorry my bad English !
Problem Description

Please list:
ccs811 sensor always fails no i2c no data

log

2018-07-12 23:42:08,519 - mycodo.daemon - ERROR - Could not activate Input controller with ID 68be24d7-9d3d-4f34-b67b-7ab3d9f56a8b: [Errno 121] Remote I/O error
Traceback (most recent call last):
  File "/var/mycodo-root/mycodo/mycodo_daemon.py", line 480, in controller_activate
    ready, cont_id)
  File "/var/mycodo-root/mycodo/controller_input.py", line 263, in __init__
    self.measure_input = CCS811Sensor(self.input_dev)
  File "/var/mycodo-root/mycodo/inputs/ccs811.py", line 29, in __init__
    self.sensor = Adafruit_CCS811(address=self.i2c_address, busnum=self.i2c_bus)
  File "/var/mycodo-root/env/lib/python3.5/site-packages/Adafruit_CCS811/Adafruit_CCS811.py", line 83, in __init__
    if(self._device.readU8(CCS811_HW_ID) != CCS811_HW_ID_CODE):
  File "/var/mycodo-root/env/lib/python3.5/site-packages/Adafruit_GPIO/I2C.py", line 148, in readU8
    result = self._bus.read_byte_data(self._address, register) & 0xFF
  File "/var/mycodo-root/env/lib/python3.5/site-packages/Adafruit_PureIO/smbus.py", line 169, in read_byte_data
    ioctl(self._device.fileno(), I2C_RDWR, request)
OSError: [Errno 121] Remote I/O error

###
Activate Sensor Error ?

Success: Input controller activated in SQL database

Error: Could not activate Input controller with ID 68be24d7-9d3d-4f34-b67b-7ab3d9f56a8b: [Errno 121] Remote I/O error

Thanks for Help

**Comment by kizniche** [comment]
It appears it's unable to communicate with the sensor. Can you verify the sensor works?

Have you successfully taken a measurement with other software or other hardware (arduino)?

Does the device show up in an I2C can with ```i2c-detect```?

**Comment by pmunz75** [comment]
ok , i2c found my id 0x5a , and a new error 

Error: Could not activate Input controller with ID 68be24d7-9d3d-4f34-b67b-7ab3d9f56a8b: Device ID returned is not correct! Please check your wiring.

**Comment by kizniche** [comment]
How long is your wire to the sensor? Are you supplying the proper voltage?

**Comment by kizniche** [comment]
Try disconnecting everything but the one sensor and use short wires. I suspect your power supply is insufficient to run all your sensors at once.

**Comment by pmunz75** [comment]
3 meters , 3 Sensors , i2c 
first = ccs811
second = BH1750
last = BME 280
all on one wire
the ccs811 no function
BH1750 OK
BME280 OK

**Comment by kizniche** [comment]
We recently got the CCS811 sensor working in Mycodo (#467).

@wflost, could you confirm the CCS811 still works for you in the latest version (6.1.4)?

**Comment by kizniche** [comment]
@pmunz75 Have you been able to acquire a measurement form the sensor with other code or other hardware (arduino)?

**Comment by wflost** [comment]
Hi Kyle and @pmunz75 

The SparksFun CCs811 is still working correctly in 6.1.4, just checked. The issues you are encountering @pmunz75 is very similar to the issues I was encountering using a generic CCS811 sensor purchased on Ebay. I have tried two different ones from Ebay the one did not detect at all, no i2c the other was showing similar issues to your issues.

**Comment by pmunz75** [comment]
Hi wflost and Kyle,
i use the Original ( Adafruit CCS811 Air Quality Sensor Breakout - VOC and eCO2 )
Link to the shop and Datasheet : https://cdn-shop.adafruit.com/product-files/3566/3566_datasheet.pdf

i2c conectet to 0x5a its OK , issues NO Data , Mycodo Daemon.log

2018-07-13 13:57:52,810 - mycodo.daemon - INFO - 41.72 MB RAM in use
2018-07-13 14:04:42,195 - mycodo.daemon - WARNING - Input controller with ID 68be24d7-9d3d-4f34-b67b-7ab3d9f56a8b not found
2018-07-13 14:04:58,512 - mycodo.daemon - ERROR - Could not activate Input controller with ID 68be24d7-9d3d-4f34-b67b-7ab3d9f56a8b: [Errno 121] Remote I/O error
Traceback (most recent call last):
  File "/var/mycodo-root/mycodo/mycodo_daemon.py", line 480, in controller_activate
    ready, cont_id)
  File "/var/mycodo-root/mycodo/controller_input.py", line 263, in __init__
    self.measure_input = CCS811Sensor(self.input_dev)
  File "/var/mycodo-root/mycodo/inputs/ccs811.py", line 29, in __init__
    self.sensor = Adafruit_CCS811(address=self.i2c_address, busnum=self.i2c_bus)
  File "/var/mycodo-root/env/lib/python3.5/site-packages/Adafruit_CCS811/Adafruit_CCS811.py", line 83, in __init__
    if(self._device.readU8(CCS811_HW_ID) != CCS811_HW_ID_CODE):
  File "/var/mycodo-root/env/lib/python3.5/site-packages/Adafruit_GPIO/I2C.py", line 148, in readU8
    result = self._bus.read_byte_data(self._address, register) & 0xFF
  File "/var/mycodo-root/env/lib/python3.5/site-packages/Adafruit_PureIO/smbus.py", line 169, in read_byte_data
    ioctl(self._device.fileno(), I2C_RDWR, request)
OSError: [Errno 121] Remote I/O error
2018-07-13 14:05:01,926 - mycodo.daemon - WARNING - Input controller with ID 68be24d7-9d3d-4f34-b67b-7ab3d9f56a8b not found
2018-07-13 14:05:10,986 - mycodo.daemon - ERROR - Could not activate Input controller with ID 68be24d7-9d3d-4f34-b67b-7ab3d9f56a8b: Device ID returned is not correct! Please check your wiring.
Traceback (most recent call last):
  File "/var/mycodo-root/mycodo/mycodo_daemon.py", line 480, in controller_activate
    ready, cont_id)
  File "/var/mycodo-root/mycodo/controller_input.py", line 263, in __init__
    self.measure_input = CCS811Sensor(self.input_dev)
  File "/var/mycodo-root/mycodo/inputs/ccs811.py", line 29, in __init__
    self.sensor = Adafruit_CCS811(address=self.i2c_address, busnum=self.i2c_bus)
  File "/var/mycodo-root/env/lib/python3.5/site-packages/Adafruit_CCS811/Adafruit_CCS811.py", line 84, in __init__
    raise Exception("Device ID returned is not correct! Please check your wiring.")
Exception: Device ID returned is not correct! Please check your wiring.
2018-07-13 16:34:23,530 - mycodo.daemon - WARNING - Input controller with ID 68be24d7-9d3d-4f34-b67b-7ab3d9f56a8b not found

**Comment by kizniche** [comment]
Have you attempted to acquire a measurement with other software or hardware (e.g. an arduino)? If not, I would suggest testing that.

Since @wflost's sensor is working, it suggests this is an issue with your hardware (i.e. wiring, sensor, power supply, pi, etc.).

**Comment by wflost** [comment]
Hi Dave 

I upgraded to 6.2.2 and everything is still working as before, there is also an issue with Adafruit_TMP it looks like the readme files have been moved. 

This may be an issue for any new installs, mine is still working fine

Thanks
Wayne


[2018-08-23 12:01:22] 
[2018-08-23 12:01:22] #### Checking for updates to optional dependencies
[2018-08-23 12:01:37] 
[2018-08-23 12:01:37] #### Installing/updating MCP342x
[2018-08-23 12:01:38] 
[2018-08-23 12:01:38] #### Installing MCP342x==0.3.3 with pip
[2018-08-23 12:02:08] Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
[2018-08-23 12:02:15] Requirement already up-to-date: MCP342x==0.3.3 in ./env/lib/python3.5/site-packages (0.3.3)
[2018-08-23 12:02:15] Requirement already satisfied, skipping upgrade: smbus-cffi in ./env/lib/python3.5/site-packages (from MCP342x==0.3.3) (0.5.1)
[2018-08-23 12:02:15] Requirement already satisfied, skipping upgrade: cffi>=1.1.0 in ./env/lib/python3.5/site-packages (from smbus-cffi->MCP342x==0.3.3) (1.11.5)
[2018-08-23 12:02:16] Requirement already satisfied, skipping upgrade: pycparser in ./env/lib/python3.5/site-packages (from cffi>=1.1.0->smbus-cffi->MCP342x==0.3.3) (2.18)
[2018-08-23 12:02:48] 
[2018-08-23 12:02:48] #### Installing/updating tsl2561
[2018-08-23 12:02:49] 
[2018-08-23 12:02:49] #### Installing tsl2561 with pip
[2018-08-23 12:03:20] Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
[2018-08-23 12:03:28] Requirement already up-to-date: tsl2561 in ./env/lib/python3.5/site-packages (3.3)
[2018-08-23 12:04:04] 
[2018-08-23 12:04:04] #### No install candidate for RPi.GPIO
[2018-08-23 12:04:04] 
[2018-08-23 12:04:04] #### Installing/updating miflora
[2018-08-23 12:04:05] 
[2018-08-23 12:04:05] #### Installing miflora==0.4 with pip
[2018-08-23 12:04:35] Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
[2018-08-23 12:04:41] Requirement already up-to-date: miflora==0.4 in ./env/lib/python3.5/site-packages (0.4)
[2018-08-23 12:04:41] Requirement already satisfied, skipping upgrade: btlewrap==0.0.2 in ./env/lib/python3.5/site-packages (from miflora==0.4) (0.0.2)
[2018-08-23 12:05:17] 
[2018-08-23 12:05:17] #### Installing/updating bluepy
[2018-08-23 12:05:18] Reading package lists...
[2018-08-23 12:05:21] Building dependency tree...
[2018-08-23 12:05:21] Reading state information...
[2018-08-23 12:05:30] libglib2.0-dev is already the newest version (2.50.3-2).
[2018-08-23 12:05:30] 0 upgraded, 0 newly installed, 0 to remove and 51 not upgraded.
[2018-08-23 12:05:30] 
[2018-08-23 12:05:30] #### Installing bluepy==1.1.4 with pip
[2018-08-23 12:06:05] Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
[2018-08-23 12:06:11] Requirement already up-to-date: bluepy==1.1.4 in ./env/lib/python3.5/site-packages (1.1.4)
[2018-08-23 12:06:46] 
[2018-08-23 12:06:46] #### Installing/updating btlewrap
[2018-08-23 12:06:46] 
[2018-08-23 12:06:46] #### Installing btlewrap==0.0.2 with pip
[2018-08-23 12:07:17] Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
[2018-08-23 12:07:23] Requirement already up-to-date: btlewrap==0.0.2 in ./env/lib/python3.5/site-packages (0.0.2)
[2018-08-23 12:08:01] 
[2018-08-23 12:08:01] #### Installing/updating Adafruit_TMP
[2018-08-23 12:08:01] 
[2018-08-23 12:08:01] #### Installing Adafruit_TMP with pip
[2018-08-23 12:08:32] Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
[2018-08-23 12:08:38] Collecting Adafruit_TMP
[2018-08-23 12:08:39]   Using cached https://files.pythonhosted.org/packages/4d/b1/6921987a5b03b615d8f662ec1bbb5dc15f194d000e3b4a84c0e9dac7a770/Adafruit_TMP-1.6.2.tar.gz
[2018-08-23 12:08:58]     Complete output from command python setup.py egg_info:
[2018-08-23 12:08:58]     Traceback (most recent call last):
[2018-08-23 12:08:58]       File "<string>", line 1, in <module>
[2018-08-23 12:08:58]       File "/tmp/pip-install-mzaqr5rj/Adafruit-TMP/setup.py", line 15, in <module>
[2018-08-23 12:08:58]         with open(path.join(here, 'README.md'), encoding='utf-8') as f:
[2018-08-23 12:08:58]       File "/home/pi/Mycodo/env/lib/python3.5/codecs.py", line 895, in open
[2018-08-23 12:08:58]         file = builtins.open(filename, mode, buffering)
[2018-08-23 12:08:58]     FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-mzaqr5rj/Adafruit-TMP/README.md'
[2018-08-23 12:08:58]     
[2018-08-23 12:08:58]     ----------------------------------------
[2018-08-23 12:09:02] 
[2018-08-23 12:09:02] #### Installing/updating update-pigpiod
[2018-08-23 12:09:02] 
[2018-08-23 12:09:03] #### Checking which pigpiod startup script is being used
[2018-08-23 12:09:03] 
[2018-08-23 12:09:03] #### Disabling installed pigpiod startup script
[2018-08-23 12:09:12] 
[2018-08-23 12:09:12] #### Enabling pigpiod startup script (1 ms sample rate)
[2018-08-23 12:09:17] 
[2018-08-23 12:09:17] #### No install candidate for smbus
[2018-08-23 12:09:17] 
[2018-08-23 12:09:17] #### Installing/updating Adafruit_MCP3008
[2018-08-23 12:09:18] 
[2018-08-23 12:09:18] #### Installing Adafruit_MCP3008 with pip
[2018-08-23 12:09:50] Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
[2018-08-23 12:09:57] Requirement already up-to-date: Adafruit_MCP3008 in ./env/lib/python3.5/site-packages (1.0.2)
[2018-08-23 12:09:57] Requirement already satisfied, skipping upgrade: Adafruit-GPIO>=0.6.5 in ./env/lib/python3.5/site-packages (from Adafruit_MCP3008) (1.0.3)
[2018-08-23 12:09:58] Requirement already satisfied, skipping upgrade: spidev in ./env/lib/python3.5/site-packages (from Adafruit-GPIO>=0.6.5->Adafruit_MCP3008) (3.2)
[2018-08-23 12:09:58] Requirement already satisfied, skipping upgrade: adafruit-pureio in ./env/lib/python3.5/site-packages (from Adafruit-GPIO>=0.6.5->Adafruit_MCP3008) (0.2.1)
[2018-08-23 12:10:30] 
[2018-08-23 12:10:30] #### Installing/updating Adafruit_BME280
[2018-08-23 12:11:03] Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
[2018-08-23 12:11:03] Obtaining adafruit-bme280 from git+git://github.com/adafruit/Adafruit_Python_BME280.git#egg=adafruit-bme280
[2018-08-23 12:11:04]   Updating ./env/src/adafruit-bme280 clone
[2018-08-23 12:11:55] Installing collected packages: adafruit-bme280
[2018-08-23 12:11:55]   Found existing installation: Adafruit-BME280 1.0
[2018-08-23 12:11:55]     Uninstalling Adafruit-BME280-1.0:
[2018-08-23 12:11:55]       Successfully uninstalled Adafruit-BME280-1.0
[2018-08-23 12:11:55]   Running setup.py develop for adafruit-bme280
[2018-08-23 12:12:34] Successfully installed adafruit-bme280
[2018-08-23 12:12:38] 
[2018-08-23 12:12:38] #### Installing/updating Adafruit_GPIO
[2018-08-23 12:12:39] 
[2018-08-23 12:12:39] #### Installing Adafruit_GPIO with pip
[2018-08-23 12:13:09] Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
[2018-08-23 12:13:15] Requirement already up-to-date: Adafruit_GPIO in ./env/lib/python3.5/site-packages (1.0.3)
[2018-08-23 12:13:15] Requirement already satisfied, skipping upgrade: spidev in ./env/lib/python3.5/site-packages (from Adafruit_GPIO) (3.2)
[2018-08-23 12:13:15] Requirement already satisfied, skipping upgrade: adafruit-pureio in ./env/lib/python3.5/site-packages (from Adafruit_GPIO) (0.2.1)
[2018-08-23 12:13:48] 
[2018-08-23 12:13:48] #### No install candidate for serial
[2018-08-23 12:13:48] 
[2018-08-23 12:13:48] #### Installing/updating w1thermsensor
[2018-08-23 12:13:48] 
[2018-08-23 12:13:48] #### Installing w1thermsensor==1.0.5 with pip
[2018-08-23 12:14:23] Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
[2018-08-23 12:14:32] Requirement already up-to-date: w1thermsensor==1.0.5 in ./env/lib/python3.5/site-packages (1.0.5)
[2018-08-23 12:14:32] Requirement already satisfied, skipping upgrade: click in ./env/lib/python3.5/site-packages (from w1thermsensor==1.0.5) (6.7)
[2018-08-23 12:15:07] 
[2018-08-23 12:15:07] #### Installing/updating Adafruit_CCS811
[2018-08-23 12:15:07] 
[2018-08-23 12:15:07] #### Installing Adafruit_CCS811 with pip
[2018-08-23 12:15:37] Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
[2018-08-23 12:15:42] Collecting Adafruit_CCS811
[2018-08-23 12:15:45]   Downloading https://files.pythonhosted.org/packages/c1/61/1e5c43e16da0c1cdb0eafd321800a9f79f7ef6acace324398bef4594c6bf/Adafruit_CCS811-0.2.tar.gz
[2018-08-23 12:16:00]     Complete output from command python setup.py egg_info:
[2018-08-23 12:16:00]     Traceback (most recent call last):
[2018-08-23 12:16:00]       File "<string>", line 1, in <module>
[2018-08-23 12:16:00]       File "/tmp/pip-install-dpnyruf1/Adafruit-CCS811/setup.py", line 17, in <module>
[2018-08-23 12:16:00]         with open(path.join(here, 'README.md'), encoding='utf-8') as f:
[2018-08-23 12:16:00]       File "/home/pi/Mycodo/env/lib/python3.5/codecs.py", line 895, in open
[2018-08-23 12:16:00]         file = builtins.open(filename, mode, buffering)
[2018-08-23 12:16:00]     FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-dpnyruf1/Adafruit-CCS811/README.md'
[2018-08-23 12:16:00]     
[2018-08-23 12:16:00]     ----------------------------------------
[2018-08-23 12:16:07] 
[2018-08-23 12:16:07] #### Installing/updating Adafruit_ADS1x15
[2018-08-23 12:16:07] 
[2018-08-23 12:16:07] #### Installing Adafruit_ADS1x15 with pip
[2018-08-23 12:16:41] Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
[2018-08-23 12:16:48] Requirement already up-to-date: Adafruit_ADS1x15 in ./env/lib/python3.5/site-packages (1.0.2)
[2018-08-23 12:16:48] Requirement already satisfied, skipping upgrade: Adafruit-GPIO>=0.6.5 in ./env/lib/python3.5/site-packages (from Adafruit_ADS1x15) (1.0.3)
[2018-08-23 12:16:48] Requirement already satisfied, skipping upgrade: spidev in ./env/lib/python3.5/site-packages (from Adafruit-GPIO>=0.6.5->Adafruit_ADS1x15) (3.2)
[2018-08-23 12:16:48] Requirement already satisfied, skipping upgrade: adafruit-pureio in ./env/lib/python3.5/site-packages (from Adafruit-GPIO>=0.6.5->Adafruit_ADS1x15) (0.2.1)
[2018-08-23 12:17:24] 
[2018-08-23 12:17:24] #### Installing/updating sht_sensor
[2018-08-23 12:17:24] 
[2018-08-23 12:17:24] #### Installing sht_sensor==18.4.2 with pip
[2018-08-23 12:17:56] Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
[2018-08-23 12:18:04] Requirement already up-to-date: sht_sensor==18.4.2 in ./env/lib/python3.5/site-packages (18.4.2)
[2018-08-23 12:18:41] 
[2018-08-23 12:18:41] #### No install candidate for Adafruit_MAX31855
[2018-08-23 12:18:41] 
[2018-08-23 12:18:41] #### Installing/updating quick2wire
[2018-08-23 12:18:42] 
[2018-08-23 12:18:42] #### Installing quick2wire-api with pip
[2018-08-23 12:19:15] Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
[2018-08-23 12:19:20] Requirement already up-to-date: quick2wire-api in ./env/lib/python3.5/site-packages (0.0.0.2)
[2018-08-23 12:19:56] 
[2018-08-23 12:19:56] #### Installing/updating tsl2591
[2018-08-23 12:20:26] Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
[2018-08-23 12:20:26] Obtaining tsl2591 from git+git://github.com/maxlklaxl/python-tsl2591.git#egg=tsl2591
[2018-08-23 12:20:26]   Updating ./env/src/tsl2591 clone
[2018-08-23 12:20:58] Requirement already satisfied, skipping upgrade: smbus-cffi in ./env/lib/python3.5/site-packages (from tsl2591) (0.5.1)
[2018-08-23 12:20:58] Requirement already satisfied, skipping upgrade: cffi>=1.1.0 in ./env/lib/python3.5/site-packages (from smbus-cffi->tsl2591) (1.11.5)
[2018-08-23 12:20:58] Requirement already satisfied, skipping upgrade: pycparser in ./env/lib/python3.5/site-packages (from cffi>=1.1.0->smbus-cffi->tsl2591) (2.18)
[2018-08-23 12:21:25] Installing collected packages: tsl2591
[2018-08-23 12:21:25]   Found existing installation: tsl2591 0.0.1
[2018-08-23 12:21:25]     Uninstalling tsl2591-0.0.1:
[2018-08-23 12:21:25]       Successfully uninstalled tsl2591-0.0.1
[2018-08-23 12:21:25]   Running setup.py develop for tsl2591
[2018-08-23 12:21:59] Successfully installed tsl2591
[2018-08-23 12:22:05] 
[2018-08-23 12:22:05] #### Installing/updating Adafruit_BMP
[2018-08-23 12:22:05] 
[2018-08-23 12:22:05] #### Installing Adafruit_BMP with pip
[2018-08-23 12:22:35] Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
[2018-08-23 12:22:40] Collecting Adafruit_BMP
[2018-08-23 12:22:41]   Using cached https://files.pythonhosted.org/packages/48/5d/a7af3359ca37b8509b8550785ee1ae7a19cdc7b5a29cfbce5bb9efb8ee86/Adafruit_BMP-1.5.3.tar.gz
[2018-08-23 12:23:06]     Complete output from command python setup.py egg_info:
[2018-08-23 12:23:06]     Traceback (most recent call last):
[2018-08-23 12:23:06]       File "<string>", line 1, in <module>
[2018-08-23 12:23:06]       File "/tmp/pip-install-fw7ypj7z/Adafruit-BMP/setup.py", line 15, in <module>
[2018-08-23 12:23:06]         with open(path.join(here, 'README.md'), encoding='utf-8') as f:
[2018-08-23 12:23:06]       File "/home/pi/Mycodo/env/lib/python3.5/codecs.py", line 895, in open
[2018-08-23 12:23:06]         file = builtins.open(filename, mode, buffering)
[2018-08-23 12:23:06]     FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-fw7ypj7z/Adafruit-BMP/README.md'
[2018-08-23 12:23:06]     
[2018-08-23 12:23:06]     ----------------------------------------
[2018-08-23 12:23:10] 
[2018-08-23 12:23:10] #### No install candidate for numpy
[2018-08-23 12:23:10] 
[2018-08-23 12:23:10] #### Installing/updating rpi_rf
[2018-08-23 12:23:10] 
[2018-08-23 12:23:10] #### Installing rpi-rf with pip
[2018-08-23 12:23:40] Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
[2018-08-23 12:23:47] Requirement already up-to-date: rpi-rf in ./env/lib/python3.5/site-packages (0.9.6)
[2018-08-23 12:23:47] Requirement already satisfied, skipping upgrade: RPi.GPIO in ./env/lib/python3.5/site-packages (from rpi-rf) (0.6.3)
[2018-08-23 12:24:19] 
[2018-08-23 12:24:19] #### Installing/updating wiringpi
[2018-08-23 12:24:19] 
[2018-08-23 12:24:19] #### Installing wiringpi
[2018-08-23 12:24:25] wiringPi Build script
[2018-08-23 12:24:25] =====================
[2018-08-23 12:24:25] 
[2018-08-23 12:24:25] 
[2018-08-23 12:24:25] WiringPi Library
[2018-08-23 12:24:26] [UnInstall]
[2018-08-23 12:24:26] [Compile] wiringPi.c
[2018-08-23 12:24:26] [Compile] wiringSerial.c
[2018-08-23 12:24:26] [Compile] wiringShift.c
[2018-08-23 12:24:26] [Compile] piThread.c
[2018-08-23 12:24:26] [Compile] piHiPri.c
[2018-08-23 12:24:33] [Compile] wiringPiSPI.c
[2018-08-23 12:24:33] [Compile] wiringPiI2C.c
[2018-08-23 12:24:35] [Compile] softPwm.c
[2018-08-23 12:24:43] [Compile] softTone.c
[2018-08-23 12:24:46] [Compile] mcp23008.c
[2018-08-23 12:24:46] [Compile] mcp23016.c
[2018-08-23 12:24:49] [Compile] mcp23017.c
[2018-08-23 12:24:57] [Compile] mcp23s08.c
[2018-08-23 12:24:58] [Compile] mcp23s17.c
[2018-08-23 12:24:58] [Compile] sr595.c
[2018-08-23 12:25:03] [Compile] pcf8574.c
[2018-08-23 12:25:09] [Compile] pcf8591.c
[2018-08-23 12:25:13] [Compile] mcp3002.c
[2018-08-23 12:25:15] [Compile] mcp3004.c
[2018-08-23 12:25:16] [Compile] mcp4802.c
[2018-08-23 12:25:17] [Compile] mcp3422.c
[2018-08-23 12:25:19] [Compile] max31855.c
[2018-08-23 12:25:20] [Compile] max5322.c
[2018-08-23 12:25:21] [Compile] ads1115.c
[2018-08-23 12:25:26] [Compile] sn3218.c
[2018-08-23 12:25:28] [Compile] bmp180.c
[2018-08-23 12:25:28] [Compile] htu21d.c
[2018-08-23 12:25:32] [Compile] ds18b20.c
[2018-08-23 12:25:32] [Compile] rht03.c
[2018-08-23 12:25:42] [Compile] drcSerial.c
[2018-08-23 12:25:46] [Compile] drcNet.c
[2018-08-23 12:25:48] [Compile] pseudoPins.c
[2018-08-23 12:25:48] [Compile] wpiExtensions.c
[2018-08-23 12:26:14] [Link (Dynamic)]
[2018-08-23 12:26:16] [Install Headers]
[2018-08-23 12:26:16] [Install Dynamic Lib]
[2018-08-23 12:26:16] 
[2018-08-23 12:26:16] WiringPi Devices Library
[2018-08-23 12:26:16] [UnInstall]
[2018-08-23 12:26:17] [Compile] ds1302.c
[2018-08-23 12:26:17] [Compile] maxdetect.c
[2018-08-23 12:26:17] [Compile] piNes.c
[2018-08-23 12:26:17] [Compile] gertboard.c
[2018-08-23 12:26:17] [Compile] piFace.c
[2018-08-23 12:26:23] [Compile] lcd128x64.c
[2018-08-23 12:26:25] [Compile] lcd.c
[2018-08-23 12:26:27] [Compile] scrollPhat.c
[2018-08-23 12:26:31] [Compile] piGlow.c
[2018-08-23 12:26:48] [Link (Dynamic)]
[2018-08-23 12:26:49] [Install Headers]
[2018-08-23 12:26:49] [Install Dynamic Lib]
[2018-08-23 12:26:49] 
[2018-08-23 12:26:49] GPIO Utility
[2018-08-23 12:26:49] [Compile] readall.c
[2018-08-23 12:26:49] [Compile] gpio.c
[2018-08-23 12:27:17] [Link]
[2018-08-23 12:27:19] [Install]
[2018-08-23 12:27:19] 
[2018-08-23 12:27:19] All Done.
[2018-08-23 12:27:19] 
[2018-08-23 12:27:19] NOTE: To compile programs with wiringPi, you need to add:
[2018-08-23 12:27:19]     -lwiringPi
[2018-08-23 12:27:19]   to your compile line(s) To use the Gertboard, MaxDetect, etc.
[2018-08-23 12:27:19]   code (the devLib), you need to also add:
[2018-08-23 12:27:19]     -lwiringPiDev
[2018-08-23 12:27:19]   to your compile line(s).
[2018-08-23 12:27:19] 
[2018-08-23 12:27:20] 
[2018-08-23 12:27:20] #### Ensuring compatible version of influxdb is installed ####
[2018-08-23 12:27:21] Correct version of InfluxDB currently installed
[2018-08-23 12:27:22] 
[2018-08-23 12:27:22] #### Upgrading Mycodo database with alembic (if needed)
[2018-08-23 12:28:04] 
[2018-08-23 12:28:04] #### Disabling installed mycodo startup script
[2018-08-23 12:28:07] #### Enabling current mycodo startup script
[2018-08-23 12:28:11] 
[2018-08-23 12:28:11] #### Compiling Translations
[2018-08-23 12:29:41] 
[2018-08-23 12:29:41] #### Updating Mycodo crontab entry
[2018-08-23 12:29:41] Crontab entry does not exist, nothing to do.
[2018-08-23 12:29:41] 
[2018-08-23 12:29:41] #### Updating Mycodo restart monitor crontab entry
[2018-08-23 12:29:42] Removing crontab entry ...
[2018-08-23 12:29:42] Appending to crontab:
[2018-08-23 12:29:42] -----------------------------------------------
[2018-08-23 12:29:42] @reboot /var/mycodo-root/env/bin/python /var/mycodo-root/mycodo/scripts/restart_daemon.py --continuouscheck &
[2018-08-23 12:29:42] -----------------------------------------------
[2018-08-23 12:29:42] To remove previously added crontab entry, run: /home/pi/Mycodo/install/crontab.sh restart_daemon --remove
[2018-08-23 12:29:42] 
[2018-08-23 12:29:43] 
[2018-08-23 12:29:43] #### Setting permissions
[2018-08-23 12:29:51] 
[2018-08-23 12:29:51] #### Restarting the Mycodo daemon
[2018-08-23 12:30:05] Mycodo previously shut down properly
[2018-08-23 12:31:08] 
[2018-08-23 12:31:08] #### Restarting nginx
[2018-08-23 12:31:18] #### Reloading mycodoflask
[2018-08-23 12:31:20] 
[2018-08-23 12:31:20] #### Connecting to http://localhost (creates Mycodo database if it doesn't exist)
[2018-08-23 12:33:38] #### Successfully connected to http://localhost
[2018-08-23 12:33:38] Done.
[2018-08-23 12:33:38] 
[2018-08-23 12:33:38] Upgrade completed successfully without errors.

**Comment by Theoi-Meteoroi** [comment]
Yup - looks like Adafruit is fiddling with their libraries and implementing policy. The TMP library is also deprecated and archived.

I tried installing the newest version manually but it looks like the only changes are in making sure setup.py is broken.  

Going to try to manually install these two sensors using the previous github versions.

**Comment by Theoi-Meteoroi** [comment]
Well. Lovely.  If you search for "archived" Adafruit repositories you find that most all the python sensor libs I've been using have been archived, with the last act seeming to break installation.  The setup.py in each was changed to make it broken then set in concrete (archived).  That would seem to be the final finger.

I'll actively avoid Adafruit hardware in the future.  And no, I'm not going to use circuitpython either. Seems google wasn't the only one to forget how not to be evil.

**Comment by kizniche** [comment]
That is unfortunate. Luckily I forked all of these repositories a while ago for just this type of occasion. I'll see what I can do to fix this, but if there are any recommendations, let me know. Should I just add the working library fil(s) to Mycodo?

**Comment by kizniche** [comment]
I could just specify version numbers of the last working version for pip to sort out, like I've done for other pip packages (https://github.com/kizniche/Mycodo/blob/master/mycodo/scripts/dependencies.sh).

**Comment by Theoi-Meteoroi** [comment]
Since I've spent a non-trivial amount with Adafruit, I complained about the final state of the libraries.  Adafruit did respond, took action with the repositories and now says these old libs are fixed:

[https://forums.adafruit.com/viewtopic.php?f=19&t=140256](url)

**Comment by kizniche** [comment]
I appreciate you taking the initiative with contacting Adafruit and being thorough with diagnosing the issues with the packages.
