### ISSUE TITLE
Dashboard no longer works after upgrade to 6.2.0

### ISSUE THREAD

**Issue by berserktron3k** [kizniche/Mycodo#516]
## Mycodo Issue Report:
  - Specific Mycodo Version: 6.2.0
 
#### Problem Description
Please list: Dashboard no longer works after upgrading to 6.2.0. Get Error 500
Mycodo Version: 6.2.0 
Python Version: 3.5.3 (default, Jan 19 2017, 14:11:04) [GCC 6.3.0 20170124] 
Database Version: 7dbc5357d3a9
Daemon Status: Running 
Daemon Process ID: 585 
Daemon RAM Usage: 44.708 MB 
Daemon Virtualenv: Yes 
Frontend RAM Usage: 46.844 MB 
Frontend Virtualenv: Yes
 
### Errors
Error 500: Internal Server Error
Something bad happened but it's probably not your fault. Letting the developers know about these issues is crucial to supporting Mycodo. Please submit a new issue on GitHub with the following error traceback (copy the entire traceback):

Error (Full Traceback):

Traceback (most recent call last):
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/pi/Mycodo/mycodo/mycodo_flask/routes_page.py", line 489, in page_dashboard
    y_axes=y_axes)
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/pi/Mycodo/mycodo/mycodo_flask/templates/pages/dashboard.html", line 3, in top-level template code
    {% set help_page = ["dashboard", _('Dashboard')] %}
  File "/home/pi/Mycodo/mycodo/mycodo_flask/templates/layout.html", line 255, in top-level template code
    {%- block body %}{% endblock -%}
  File "/home/pi/Mycodo/mycodo/mycodo_flask/templates/pages/dashboard.html", line 788, in block "body"
    {% include 'pages/dashboard_options/display_graph.html' %}
  File "/home/pi/Mycodo/mycodo/mycodo_flask/templates/pages/dashboard_options/display_graph.html", line 85, in top-level template code
    {% if each_graph.enable_manual_y_axis and
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/jinja2/environment.py", line 411, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'collections.OrderedDict object' has no attribute 'percent'

### Steps to Reproduce the issue:
How can this issue be reproduced?

Upgrade to 6.2? Not quite sure
 
### Additional Notes
Is there anything that should be added to make it easier
to address this issue?

**Comment by kizniche** [comment]
Can you check that all your math controllers have a measurement unit set?

**Comment by berserktron3k** [comment]
I've got a PID set up that, as far as I can tell, is configured properly.

An input (DHT22), the looks like it is configured properly (units set, etc).

4 outputs (no units to set there), and 2 conditionals that simply control
an output based on time of day.

Other than that, no Math configured other than what's included out of the
box.

Brady Hummel

**Comment by kizniche** [comment]
I'll look into this when I can get to my development system. I may have to take a look at your database (mycodo.db) to really understand the issue. Make sure, if you do send your database, don't post it publicly here in github, send it to my email address.

**Comment by kizniche** [comment]
I just released v6.2.1, which adds a new configuration menu that has the option to delete all dashboard elements. I added this because it appears too difficult to diagnose individual issues that may have arisen from the 6.2.0 upgrade, causing a misconfiguration of any of a number of dashboard elements. By deleting all dashboard elements, this will allow you to access the Dashboard page again and rebuild your Dashboard. I'm sorry to have to do this, but I feel it is the best way to approach this without investing a lot of effort to find issues that may be resolved by rebuilding the dashboard. Please let me know if there are any issues with the new feature and if you experience any new issues related to adding new dashboard elements. If there are new issues related to creating new dashboard elements, I will do my best to address them, as I believe addressing these new issues will be more productive than the many potential issues that could have resulted from the 6.2.0 upgrade.

**Comment by berserktron3k** [comment]
Good enough for me. Seems to have worked great. Thanks!

Brady Hummel

**Comment by berserktron3k** [comment]
Spoke too soon. I think I found the issue. If I add durations to a graph
for outputs, as soon as I hit save, I had the same issue.

Brady Hummel

**Comment by berserktron3k** [comment]
Sorry, disregard that... it's not the duration that caused it, it was
enabling this: Enable Manual Y-Axis Min/Max

Brady Hummel

**Comment by kizniche** [comment]
I just fixed the manual y-axis issue and it will be available in the next release. Thanks for the support.
