### ISSUE TITLE
MH-Z16 serial sensor activation fails

### ISSUE THREAD

**Issue by Theoi-Meteoroi** [kizniche/Mycodo#520]
## Mycodo Issue Report:
  - Specific Mycodo Version: 6.2.2
 
#### Problem Description
Please list:

MH-Z16 serial device fails to configure with python error with v6.2.2
Last known working version v5.7.3

Tested MH-Z16 I2C sensor.   That interface works fine.

 
### Errors

2018-08-30 00:35:34,254 - mycodo.daemon - ERROR - Could not activate Input controller with ID c9e61945-e9c8-49bb-bb83-4b2bd6582c4d: invalid literal for int() with base 16: 'Tx/Rx'
Traceback (most recent call last):
  File "/var/mycodo-root/mycodo/mycodo_daemon.py", line 481, in controller_activate
    ready, cont_id)
  File "/var/mycodo-root/mycodo/controller_input.py", line 321, in __init__
    self.measure_input = MHZ16Sensor(self.input_dev)
  File "/var/mycodo-root/mycodo/inputs/mh_z16.py", line 45, in __init__
    self.i2c_address = int(str(input_dev.location), 16)
ValueError: invalid literal for int() with base 16: 'Tx/Rx'

### Steps to Reproduce the issue:

Configure MH-Z16 serial sensor to /dev/ttyAMA0
Activate sensor

### Additional Notes
Is there anything that should be added to make it easier
to address this issue?

**Comment by kizniche** [comment]
Thanks. I see the issue. I'll work on getting a fix and new release out.
