### ISSUE TITLE
BMP280 showing nodata

### ISSUE THREAD

**Issue by wflost** [kizniche/Mycodo#522]
## Mycodo Issue Report:
  - Specific Mycodo Version: 6.2.2
 
#### Problem Description
Please list:
BMP280 sensor is showing "No Data" since last update. You have added the sensor in Apr 2017 
#233 

I have added a 3 sensor on a single board, it has a ccs811, SI7021 and BMP280 on the board, is this a bad connection on the board to produce this error in the log? Is my I2C to fast or slow.

I also have a I2C mux to give me additional I2C channels

  - what were you trying to do
  - specific setup details that are involved
 
### Errors
  - List any errors you encountered.
  - Copy and pasting crash logs, or link to any specific
code lines you've isolated (please use GitHub permalinks for this)

2018-09-03 21:13:33,885 - mycodo.inputs.bmp280_7 - ERROR - BMP280Sensor raised an exception when taking a reading: unsupported operand type(s) for >>: 'float' and 'int'
Traceback (most recent call last):
  File "/var/mycodo-root/mycodo/inputs/bmp280.py", line 165, in read
    self._altitude) = self.get_measurement()
  File "/var/mycodo-root/mycodo/inputs/bmp280.py", line 144, in get_measurement
    pressure_pa = self.read_pressure()
  File "/var/mycodo-root/mycodo/inputs/bmp280.py", line 288, in read_pressure
    var1 = (self.cal_REGISTER_DIG_P9 * (p >> 13) * (p >> 13)) >> 25
TypeError: unsupported operand type(s) for >>: 'float' and 'int'
2018-09-03 21:15:33,835 - mycodo.inputs.bmp280_7 - ERROR - BMP280Sensor raised an exception when taking a reading: unsupported operand type(s) for >>: 'float' and 'int'
Traceback (most recent call last):
  File "/var/mycodo-root/mycodo/inputs/bmp280.py", line 165, in read
    self._altitude) = self.get_measurement()
  File "/var/mycodo-root/mycodo/inputs/bmp280.py", line 144, in get_measurement
    pressure_pa = self.read_pressure()
  File "/var/mycodo-root/mycodo/inputs/bmp280.py", line 288, in read_pressure
    var1 = (self.cal_REGISTER_DIG_P9 * (p >> 13) * (p >> 13)) >> 25
TypeError: unsupported operand type(s) for >>: 'float' and 'int'
2018-09-03 21:15:33,851 - mycodo.input_22222ae3 - ERROR - StopIteration raised. Possibly could not read input. Ensure it's connected properly and detected.
2018-09-03 21:17:34,050 - mycodo.inputs.bmp280_7 - ERROR - BMP280Sensor raised an exception when taking a reading: unsupported operand type(s) for >>: 'float' and 'int'
Traceback (most recent call last):
  File "/var/mycodo-root/mycodo/inputs/bmp280.py", line 165, in read
    self._altitude) = self.get_measurement()
  File "/var/mycodo-root/mycodo/inputs/bmp280.py", line 144, in get_measurement
    pressure_pa = self.read_pressure()
  File "/var/mycodo-root/mycodo/inputs/bmp280.py", line 288, in read_pressure
    var1 = (self.cal_REGISTER_DIG_P9 * (p >> 13) * (p >> 13)) >> 25
TypeError: unsupported operand type(s) for >>: 'float' and 'int'

### Steps to Reproduce the issue:
How can this issue be reproduced?
 1. step 1
 2. step 2...
 3. etc
 
### Additional Notes
Is there anything that should be added to make it easier
to address this issue?

**Comment by Theoi-Meteoroi** [comment]
I took a look at this one since I have the same combination sensor module and saw the same problem with the BMP280 code.  

I think I found the problem and the fix.  Mycodo seems to be missing some changes for Python3 that the original author added.  There was one other change not in that diff I had to make.
The diff is here:
[https://github.com/vitally/BMP280/commit/0874583db72038c2862b016a5a28367e7103f5bc#diff-c9282843e9fbb62e6032f72ce6c38343](url)

I'll put together a pull request with the changes I'm testing now.

I've been testing all the sensor types I have and found a few aren't working or have bogus values.  The other one I noticed (silently) failing is the BMP180. I don't know if I'll get around to looking at that one.

**Comment by wflost** [comment]
Thanks Dave, I have had three of these before and one of the sensors was DOA. So I wanted to make sure it is the case again or if anyone else is experiencing the issue. You are using the SI7021, which input do you select?
Thanks
Wayne

**Comment by Theoi-Meteoroi** [comment]
I haven't tried to use the Si7021 - even though I have a bunch of them from a sale at DFrobot.  We will need to find a suitable Python3 driver to integrate with Mycodo. I don't know if Kyle has looked at it and selected any candidates.   I'll research that some today and see what is available.  

The changes above are pretty simple if you look at the diff and modify your local copy to be identical.  You don't even have to restart the backend. Just be sure to deactivate/reactivate the sensor and it should pick up the changes.

**Comment by kizniche** [comment]
It looks like [pi-si7021](https://pypi.org/project/pi-si7021/) might be a good library to test. It appears to be more recently-updated than [Si7021](https://pypi.org/project/Si7021/).

**Comment by wflost** [comment]
Hi Kyle,

Happy to test, I have it running on the SHT2x at the moment, I have also opened #521 to keep the issues/enhancements separated

Thanks
Wayne

**Comment by Theoi-Meteoroi** [comment]
I'll give the pi-si7021 repo a go with my device.

**Comment by wflost** [comment]
Tested the bmp280.py change an I have data being collected

Thanks Dave
