### ISSUE TITLE
Crash report for output

### ISSUE THREAD

**Issue by alonrab** [kizniche/Mycodo#612]
## Mycodo Issue Report:
  7.1.3
 
#### Problem Description
Please list:
Hi All, run into this error for outputs set up, 
After pressing: add output for atlas i2c pump signal crash error accrued. 
Restart / did not solved it, pressing output in setup generate the same error 
Any suggestions? many thanks!
### Errors

```
 Error 500: Internal Server Error
Something bad happened but it's probably not your fault. Letting the developers know about these issues is crucial to supporting Mycodo. Please submit a new issue on GitHub with the following error traceback (copy the entire traceback):

Error (Full Traceback):

Traceback (most recent call last):
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/pi/Mycodo/mycodo/mycodo_flask/routes_page.py", line 1546, in page_output
    user=user)
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/pi/Mycodo/mycodo/mycodo_flask/templates/pages/output.html", line 3, in top-level template code
    {% set help_page = ["output", dict_translation['output']['title']] %}
  File "/home/pi/Mycodo/mycodo/mycodo_flask/templates/layout.html", line 260, in top-level template code
    {%- block body %}{% endblock -%}
  File "/home/pi/Mycodo/mycodo/mycodo_flask/templates/pages/output.html", line 230, in block "body"
    {% include 'pages/output_options/'+each_output_template %}
  File "/home/pi/Mycodo/mycodo/mycodo_flask/templates/pages/output_options/atlas_ezo_pmp.html", line 4, in top-level template code
    {{form_mod_output.i2c_location.label(class_='control-label')}}
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'mycodo.mycodo_flask.forms.forms_output.OutputMod object' has no attribute 'i2c_location'
```

### Steps to Reproduce the issue:
How can this issue be reproduced?
 1. step 1
 2. step 2...
 3. etc
 
### Additional Notes
Is there anything that should be added to make it easier
to address this issue?

**Comment by kizniche** [comment]
Navigate to the Info page (https://IPaddress/info) and see if you have a database version mismatch ("Database Version" is red, not green). If so, you will need to delete your database and reload the frontend to generate a new database.

**Comment by kizniche** [comment]
If you have a DB version mismatch, you can rename/delete ```~/Mycodo/databases/mycodo.db``` or [upgrade to master](https://github.com/kizniche/Mycodo/wiki/Updating-to-Github-Master-Branch), then do to Config -> Diagnostic and use the Delete Settings Database option to do it automatically.

**Comment by kizniche** [comment]
Now, there's another issue of the pump output actually working. I don't believe the person who was testing the code (I don't have the pump to test) continued replying so we could get all the bugs worked out. If you're willing, can you try to activate the pump (instruct it to dispense 5 ml, for example), and copy the output from the Daemon Log?

**Comment by kizniche** [comment]
You can start replying in #562 and I'll close this issue.
