### ISSUE TITLE
After Update issue

### ISSUE THREAD

**Issue by cohe4ko** [kizniche/Mycodo#659]
## Mycodo Issue Report:
  - Specific Mycodo Version:

#### Checking for updates to dependencies
Traceback (most recent call last):
  File "/home/pi/Mycodo/mycodo/utils/update_installed_dependencies.py", line 58, in <module>
    installed_deps = get_installed_dependencies()
  File "/home/pi/Mycodo/mycodo/utils/update_installed_dependencies.py", line 25, in get_installed_dependencies
    dict_inputs = parse_input_information()
  File "/home/pi/Mycodo/mycodo/utils/inputs.py", line 119, in parse_input_information
    input_custom = load_module_from_file(full_path)
  File "/home/pi/Mycodo/mycodo/utils/inputs.py", line 69, in load_module_from_file
    spec.loader.exec_module(input_custom)
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/pi/Mycodo/mycodo/inputs/th1x.py", line 9, in <module>
    import requests
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/requests/__init__.py", line 95, in <module>
    from urllib3.contrib import pyopenssl
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 13, in <module>
    from cryptography.hazmat.primitives.asymmetric import dsa, rsa
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/primitives/asymmetric/rsa.py", line 14, in <module>
    from cryptography.hazmat.backends.interfaces import RSABackend
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/backends/__init__.py", line 7, in <module>
    import pkg_resources
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws = cls()
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 567, in __init__
    self.add_entry(entry)
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 623, in add_entry
    for dist in find_distributions(entry, True):
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2056, in find_on_path
    for dist in factory(fullpath):
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2126, in distributions_from_metadata
    root, entry, metadata, precedence=DEVELOP_DIST,
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2583, in from_location
    py_version=py_version, platform=platform, **kw
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2985, in _reload_version
    md_version = self._get_version()
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2763, in _get_version
    version = _version_from_file(lines)
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2547, in _version_from_file
    line = next(iter(version_lines), '')
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2758, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1423, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/home/pi/Mycodo/env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1420, in get_metadata
    return value.decode('utf-8') if six.PY3 else value
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8a in position 45188: invalid start byte

 
### Additional Notes
Is there anything that should be added to make it easier
to address this issue?

**Comment by kizniche** [comment]
Provide more information by filling out all the information on the issue template.
