### ISSUE TITLE
RPyC AsyncResultTimeout("result expired") issue

### ISSUE THREAD

**Issue by kizniche** [kizniche/Mycodo#679]
As a result of this issue that I have not been able to fix, nor have I been able to find others with similar issues that managed to solve the issue, I'm going to explore the use of RPyC alternatives to handle remote procedure calls. This issue will track my progress with commits and notes.

Issues affected by this: #671

**Comment by kizniche** [comment]
List of alternatives: https://stackoverflow.com/questions/1879971/what-is-the-current-choice-for-doing-rpc-in-python

I'll be attempting to use PyRo4 first.

**Comment by kizniche** [comment]
I successfully replaced RPyC with PyRo4 and am conducting a long-duration stability test. I'll report back in a week or so with results.

**Comment by kizniche** [comment]
So far Pyro4 has been working perfectly.

**Comment by kizniche** [comment]
Well, this error occurred today. This may have to do with resource availability (e.g. RAM). This is one of my last systems still running Raspbian Stretch (9). I'm going to upgrade to Buster (10), which uses a more recent Python version and see if there's any improvement with resource-handling.

```
2019-08-21 16:03:02,823 - ERROR - mycodo.controller_pid_3f9829ac - Run Error: receiving: timeout
Traceback (most recent call last):
  File "/var/mycodo-root/env/lib/python3.5/site-packages/Pyro4/socketutil.py", line 151, in receiveData
    data = sock.recv(size, socket.MSG_WAITALL)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/mycodo-root/mycodo/controller_pid.py", line 232, in run
    self.check_pid()
  File "/var/mycodo-root/mycodo/controller_pid.py", line 392, in check_pid
    self.manipulate_output()
  File "/var/mycodo-root/mycodo/controller_pid.py", line 754, in manipulate_output
    min_off=self.raise_min_off_duration)
  File "/var/mycodo-root/mycodo/mycodo_client.py", line 162, in output_on
    duty_cycle=duty_cycle, trigger_conditionals=trigger_conditionals)
  File "/var/mycodo-root/env/lib/python3.5/site-packages/Pyro4/core.py", line 185, in __call__
    return self.__send(self.__name, args, kwargs)
  File "/var/mycodo-root/env/lib/python3.5/site-packages/Pyro4/core.py", line 453, in _pyroInvoke
    msg = message.Message.recv(self._pyroConnection, [message.MSG_RESULT], hmac_key=self._pyroHmacKey)
  File "/var/mycodo-root/env/lib/python3.5/site-packages/Pyro4/message.py", line 168, in recv
    msg = cls.from_header(connection.recv(cls.header_size))
  File "/var/mycodo-root/env/lib/python3.5/site-packages/Pyro4/socketutil.py", line 463, in recv
    return receiveData(self.sock, size)
  File "/var/mycodo-root/env/lib/python3.5/site-packages/Pyro4/socketutil.py", line 159, in receiveData
    raise TimeoutError("receiving: timeout")
Pyro4.errors.TimeoutError: receiving: timeout
```
