### ISSUE TITLE
no data

### ISSUE THREAD

**Issue by leoneo** [kizniche/Mycodo#738]
### Describe the problem/bug

no data from all sensors with new fresh install

### Versions:

 - Mycodo Version: [8.2.3]
 - Raspberry Pi Version: [2]
 - Raspbian OS Version: [ Buster Lite]

### Reproducibility

daemon log :

self.bus.write_byte(self.I2C_ADDR, bits_high)
  File "/var/mycodo-root/env/lib/python3.7/site-packages/smbus2/smbus2.py", line 393, in write_byte
    ioctl(self.fd, I2C_SMBUS, msg)
OSError: [Errno 121] Remote I/O error
2020-01-29 13:42:28,844 - INFO - mycodo.controllers.controller_input_847be534 - Activated in 605.0 ms
2020-01-29 13:42:28,847 - DEBUG - mycodo.devices.atlas_scientific_i2c_102_1 - AtlasScientificI2C raised an exception when taking a reading: [Errno 121] Remote I/O error
2020-01-29 13:42:28,848 - ERROR - mycodo.inputs.atlas_ph_847be534 - Sensor read unsuccessful: [Errno 121] Remote I/O error
2020-01-29 13:42:28,849 - ERROR - mycodo.inputs.atlas_ph_847be534 - InputModule raised an exception when taking a reading: float() argument must be a string or a number, not 'NoneType'
2020-01-29 13:42:39,944 - ERROR - mycodo.devices.lcd_generic_da8ffd84 - Could not initialize LCD. Check your configuration and wiring. Error: [Errno 121] Remote I/O error
2020-01-29 13:42:39,946 - ERROR - mycodo.controllers.controller_lcd_da8ffd84 - IOError: Unable to output to LCD.
Traceback (most recent call last):
  File "/var/mycodo-root/mycodo/controllers/controller_lcd.py", line 139, in loop
    self.output_lcds()
  File "/var/mycodo-root/mycodo/controllers/controller_lcd.py", line 474, in output_lcds
    self.lcd_out.lcd_write_lines(line_1, line_2, line_3, line_4)
  File "/var/mycodo-root/mycodo/devices/lcd_generic.py", line 111, in lcd_write_lines
    self.lcd_string_write(line_1, 1)
  File "/var/mycodo-root/mycodo/devices/lcd_generic.py", line 105, in lcd_string_write
    self.lcd_byte(line_write, self.LCD_CMD)
  File "/var/mycodo-root/mycodo/devices/lcd_generic.py", line 87, in lcd_byte
    self.bus.write_byte(self.I2C_ADDR, bits_high)
  File "/var/mycodo-root/env/lib/python3.7/site-packages/smbus2/smbus2.py", line 393, in write_byte
    ioctl(self.fd, I2C_SMBUS, msg)
OSError: [Errno 121] Remote I/O error
2020-01-29 13:42:43,712 - DEBUG - mycodo.devices.atlas_scientific_i2c_102_1 - AtlasScientificI2C raised an exception when taking a reading: [Errno 121] Remote I/O error
2020-01-29 13:42:43,713 - ERROR - mycodo.inputs.atlas_ph_847be534 - Sensor read unsuccessful: [Errno 121] Remote I/O error
2020-01-29 13:42:43,714 - ERROR - mycodo.inputs.atlas_ph_847be534 - InputModule raised an exception when taking a reading: float() argument must be a string or a number, not 'NoneType'
2020-01-29 13:42:58,749 - DEBUG - mycodo.devices.atlas_scientific_i2c_102_1 - AtlasScientificI2C raised an exception when taking a reading: [Errno 121] Remote I/O error
2020-01-29 13:42:58,750 - ERROR - mycodo.inputs.atlas_ph_847be534 - Sensor read unsuccessful: [Errno 121] Remote I/O error
2020-01-29 13:42:58,751 - ERROR - mycodo.inputs.atlas_ph_847be534 - InputModule raised an exception when taking a reading: float() argument must be a string or a number, not 'NoneType'
2020-01-29 13:42:58,751 - ERROR - mycodo.controllers.controller_input_847be534 - StopIteration raised 3 times. Possibly could not read input. Ensure it's connected properly and detected.
2020-01-29 13:43:06,365 - INFO - mycodo.controllers.controller_input_4b0393c6 - Activated in 613.1 ms
2020-01-29 13:43:06,374 - DEBUG - mycodo.devices.atlas_scientific_i2c_102_1 - AtlasScientificI2C raised an exception when taking a reading: [Errno 121] Remote I/O error
2020-01-29 13:43:06,376 - ERROR - mycodo.inputs.atlas_pt1000_4b0393c6 - Sensor read unsuccessful: [Errno 121] Remote I/O error
2020-01-29 13:43:06,377 - ERROR - mycodo.inputs.atlas_pt1000_4b0393c6 - InputModule raised an exception when taking a reading: float() argument must be a string or a number, not 'NoneType'
2020-01-29 13:43:10,159 - ERROR - mycodo.devices.lcd_generic_da8ffd84 - Could not initialize LCD. Check your configuration and wiring. Error: [Errno 121] Remote I/O error
2020-01-29 13:43:10,161 - ERROR - mycodo.controllers.controller_lcd_da8ffd84 - IOError: Unable to output to LCD.
Traceback (most recent call last):
  File "/var/mycodo-root/mycodo/controllers/controller_lcd.py", line 139, in loop
    self.output_lcds()
  File "/var/mycodo-root/mycodo/controllers/controller_lcd.py", line 474, in output_lcds
    self.lcd_out.lcd_write_lines(line_1, line_2, line_3, line_4)
  File "/var/mycodo-root/mycodo/devices/lcd_generic.py", line 111, in lcd_write_lines
    self.lcd_string_write(line_1, 1)
  File "/var/mycodo-root/mycodo/devices/lcd_generic.py", line 105, in lcd_string_write
    self.lcd_byte(line_write, self.LCD_CMD)
  File "/var/mycodo-root/mycodo/devices/lcd_generic.py", line 87, in lcd_byte
    self.bus.write_byte(self.I2C_ADDR, bits_high)
  File "/var/mycodo-root/env/lib/python3.7/site-packages/smbus2/smbus2.py", line 393, in write_byte
    ioctl(self.fd, I2C_SMBUS, msg)
OSError: [Errno 121] Remote I/O error
2020-01-29 13:43:13,736 - DEBUG - mycodo.devices.atlas_scientific_i2c_102_1 - AtlasScientificI2C raised an exception when taking a reading: [Errno 121] Remote I/O error
2020-01-29 13:43:13,738 - ERROR - mycodo.inputs.atlas_ph_847be534 - Sensor read unsuccessful: [Errno 121] Remote I/O error
2020-01-29 13:43:13,738 - ERROR - mycodo.inputs.atlas_ph_847be534 - InputModule raised an exception when taking a reading: float() argument must be a string or a number, not 'NoneType'
2020-01-29 13:43:21,215 - DEBUG - mycodo.devices.atlas_scientific_i2c_102_1 - AtlasScientificI2C raised an exception when taking a reading: [Errno 121] Remote I/O error
2020-01-29 13:43:21,216 - ERROR - mycodo.inputs.atlas_pt1000_4b0393c6 - Sensor read unsuccessful: [Errno 121] Remote I/O error
2020-01-29 13:43:21,217 - ERROR - mycodo.inputs.atlas_pt1000_4b0393c6 - InputModule raised an exception when taking a reading: float() argument must be a string or a number, not 'NoneType'
2020-01-29 13:43:28,682 - DEBUG - mycodo.devices.atlas_scientific_i2c_102_1 - AtlasScientificI2C raised an exception when taking a reading: [Errno 121] Remote I/O error
2020-01-29 13:43:28,683 - ERROR - mycodo.inputs.atlas_ph_847be534 - Sensor read unsuccessful: [Errno 121] Remote I/O error
2020-01-29 13:43:28,684 - ERROR - mycodo.inputs.atlas_ph_847be534 - InputModule raised an exception when taking a reading: float() argument must be a string or a number, not 'NoneType'

**Comment by leoneo** [comment]
everything worked fine with v8.2.2. I installed with sudo apt-get install python-smbus and sudo apt-get install i2c-tools, to test a new sensor (Atlas RGB). No more i2c sensors work, so I reinstalled raspbian and mycodo. And nothing works anymore.

**Comment by leoneo** [comment]
I found the problem. the BMP180 sensor is de-soldered, no longer operating the other i2c.
and I had a database error solved by Deleting and Recreating the InfluxDB.
