### ISSUE TITLE
Energy Usage Report on 8.2.5 error 500

### ISSUE THREAD

**Issue by NannoB-hub** [kizniche/Mycodo#745]
Traceback (most recent call last):
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask_restx/api.py", line 600, in error_router
    return original_handler(e)
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/pi/Mycodo/mycodo/mycodo_flask/routes_page.py", line 2083, in page_usage
    output_stats = return_output_usage(misc, output)
  File "/home/pi/Mycodo/mycodo/utils/tools.py", line 107, in return_output_usage
    past_1d_hours = output_sec_on(each_output.unique_id, 86400) / 3600
  File "/home/pi/Mycodo/mycodo/utils/influx.py", line 495, in output_sec_on
    if output.is_on():
  File "/home/pi/Mycodo/mycodo/databases/models/output.py", line 89, in is_on
    return self.on_state == GPIO.input(self.pin)
NameError: name 'GPIO' is not defined

**Comment by kizniche** [comment]
Thanks for the bug report. The fix will be incorporated in the next release, which will ikely be this weekend.
