### ISSUE TITLE
Cannot install Mycodo on Desktop version of Raspberry Pi OS

### ISSUE THREAD

**Issue by Mark0Mi** [kizniche/Mycodo#792]
### Describe the problem/bug
fresh pi install
first time to install mycodo (nothing else installed)
install errors 
seems to be the same error as in https://github.com/kizniche/mycodo/issues/614
web service does not start 
-> fixed it by changing the requirements files and switched version of bcrypt to 3.1.4
--> also did the stuff that was described in issues/614 (but I think only bcrypt to 3.1.4 is necessary) 

### Versions:
 - Mycodo Version: 8.5.8
 - Raspberry Pi Version: [4]

### Reproducibility
blank install of raspbian
execute curl... to install mycodo 
wait for webservice not starting.. 

setup.log: (where the error is) 
Collecting bcrypt==3.1.7
  Using cached bcrypt-3.1.7.tar.gz (42 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /home/pi/Mycodo/env/bin/python /home/pi/Mycodo/env/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpp2pkd8j_
         cwd: /tmp/pip-install-x5guumk6/bcrypt
    Complete output (34 lines):
    Traceback (most recent call last):
      File "/home/pi/Mycodo/env/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/home/pi/Mycodo/env/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/home/pi/Mycodo/env/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 140, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 126, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 240, in <module>
        **keywords_with_side_effects(sys.argv)
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.7/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 447, in __init__
        k: v for k, v in attrs.items()
      File "/usr/lib/python3.7/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 739, in finalize_options
        ep.load()(self, ep.name, value)
      File "/tmp/pip-build-env-ebj4pxwl/overlay/lib/python3.7/site-packages/cffi/setuptools_ext.py", line 217, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/tmp/pip-build-env-ebj4pxwl/overlay/lib/python3.7/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/tmp/pip-build-env-ebj4pxwl/overlay/lib/python3.7/site-packages/cffi/setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "src/build_bcrypt.py", line 21, in <module>
        ffi = FFI()
      File "/tmp/pip-build-env-ebj4pxwl/overlay/lib/python3.7/site-packages/cffi/api.py", line 56, in __init__
        backend.__version__, backend.__file__))
    Exception: Version mismatch: this is the 'cffi' package version 1.14.0, located in '/tmp/pip-build-env-ebj4pxwl/overlay/lib/python3.7/site-packages/cffi/api.py'.  When we import the top-level '_cffi_backend' extension module, we get version 1.12.2, located in '/usr/lib/python3/dist-packages/_cffi_backend.cpython-37m-arm-linux-gnueabihf.so'.  The two versions should be equal; check your installation.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/pi/Mycodo/env/bin/python /home/pi/Mycodo/env/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpp2pkd8j_ Check the logs for full command output.
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already up-to-date: pylibftdi==0.18.1 in ./env/lib/python3.7/site-packages (from -r /home/pi/Mycodo/install/requirements-rpi.txt (line 2)) (0.18.1)
Requirement already up-to-date: RPi.GPIO in /usr/lib/python3/dist-packages (from -r /home/pi/Mycodo/install/requirements-rpi.txt (line 3)) (0.7.0)
Requirement already up-to-date: smbus2==0.3.0 in ./env/lib/python3.7/site-packages (from -r /home/pi/Mycodo/install/requirements-rpi.txt (line 4)) (0.3.0)
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple

**Comment by kizniche** [comment]
No, that issue has long been fixed. You're experiencing #787, for which the fix has not been released. It will be love in v8.6.0
