### ISSUE TITLE
Error setup -> data after removing pi default admin user

### ISSUE THREAD

**Issue by stardawg** [kizniche/Mycodo#797]
Changed raspberrypi admin user

Traceback (most recent call last):
  File "/home/[user]/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/[user]/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/[user]/Mycodo/env/lib/python3.7/site-packages/flask_restx/api.py", line 639, in error_router
    return original_handler(e)
  File "/home/[user]/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/[user]/Mycodo/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/[user]/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/[user]/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/[user]/Mycodo/env/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/[user]/Mycodo/mycodo/mycodo_flask/routes_page.py", line 1965, in page_data
    elif not dpkg_package_exists('ow-shell'):
  File "/home/[user]/Mycodo/mycodo/utils/system_pi.py", line 83, in dpkg_package_exists
    _, _, stat = cmd_output(cmd)
  File "/home/[user]/Mycodo/mycodo/utils/system_pi.py", line 249, in cmd_output
    pw_record = pwd.getpwnam(user)
KeyError: "getpwnam(): name not found: 'pi'"

**Comment by kizniche** [comment]
I think you found your issue: you removed user pi.
