### ISSUE TITLE
Server error when adding data "Linux: Python 3 Code: Store Value(s)

### ISSUE THREAD

**Issue by reymart081678** [kizniche/Mycodo#846]
Mycodo Version: 8.8.2
Python Version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]
Database Version: 0e150fb8020b
Daemon Status: Running
Daemon Process ID: 791
Daemon RAM Usage: 41.936 MB
Daemon Virtualenv: Yes
Frontend Process ID: 398
Frontend RAM Usage: 51.984 MB
Frontend Virtualenv: Yes

Error 500: Internal Server Error
Something bad happened but it's probably not your fault. Letting the developers know about these issues is crucial to supporting Mycodo. Please submit a new issue on GitHub with the following error traceback (copy the entire traceback):

Error (Full Traceback):

Traceback (most recent call last):
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask_restx/api.py", line 639, in error_router
    return original_handler(e)
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/pi/Mycodo/mycodo/mycodo_flask/routes_page.py", line 1848, in page_data
    unmet_dependencies = utils_input.input_add(form_add_input)
  File "/home/pi/Mycodo/mycodo/mycodo_flask/utils/utils_input.py", line 237, in input_add
    new_input, dict_inputs[new_input.device])
  File "/home/pi/Mycodo/mycodo/inputs/python_code.py", line 65, in execute_at_creation
    generate_code(unique_id, new_input)
  File "/home/pi/Mycodo/mycodo/inputs/python_code.py", line 47, in generate_code
    indented_code = textwrap.indent(new_input.cmd_command, ' ' * 8)
AttributeError: 'dict' object has no attribute 'cmd_command'

**Comment by kizniche** [comment]
Thanks for the bug report. I'll investigate.

**Comment by kizniche** [comment]
v8.8.3 released with the fix
