### ISSUE TITLE
Setup>Data page unavailable

### ISSUE THREAD

**Issue by anon72c** [kizniche/Mycodo#851]
Traceback (most recent call last):
  File "/home/CloneTent/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/CloneTent/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/CloneTent/Mycodo/env/lib/python3.7/site-packages/flask_restx/api.py", line 639, in error_router
    return original_handler(e)
  File "/home/CloneTent/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/CloneTent/Mycodo/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/CloneTent/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/CloneTent/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/CloneTent/Mycodo/env/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/CloneTent/Mycodo/mycodo/mycodo_flask/routes_page.py", line 2007, in page_data
    elif not dpkg_package_exists('ow-shell'):
  File "/home/CloneTent/Mycodo/mycodo/utils/system_pi.py", line 230, in dpkg_package_exists
    _, _, stat = cmd_output(cmd)
  File "/home/CloneTent/Mycodo/mycodo/utils/system_pi.py", line 396, in cmd_output
    pw_record = pwd.getpwnam(user)
KeyError: "getpwnam(): name not found: 'pi'"

**Comment by kizniche** [comment]
From your error, it appears you're not installing Mycodo using the recommended method. I'll only provide support for the install method specified in the install instructions.
