### ISSUE TITLE
Mycodo fails when it can't find user 'pi'

### ISSUE THREAD

**Issue by mihakralj** [kizniche/Mycodo#922]
For security reasons I always either delete or change the name of default user - pi
This is what Mycodo returns in web interface when I go to /data for the first time. See the last line: **getpwnam(): name not found: 'pi'**

```
Traceback (most recent call last):
  File "/home/iharvest/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/iharvest/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/iharvest/Mycodo/env/lib/python3.7/site-packages/flask_restx/api.py", line 639, in error_router
    return original_handler(e)
  File "/home/iharvest/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/iharvest/Mycodo/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/iharvest/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/iharvest/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/iharvest/Mycodo/env/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/iharvest/Mycodo/mycodo/mycodo_flask/routes_page.py", line 2007, in page_data
    elif not dpkg_package_exists('ow-shell'):
  File "/home/iharvest/Mycodo/mycodo/utils/system_pi.py", line 230, in dpkg_package_exists
    _, _, stat = cmd_output(cmd)
  File "/home/iharvest/Mycodo/mycodo/utils/system_pi.py", line 396, in cmd_output
    pw_record = pwd.getpwnam(user)
KeyError: "getpwnam(): name not found: 'pi'"
```

**Comment by mihakralj** [comment]
Ugh, this is clearly a duplicate... :-)
I should read before I post new issues. Closing due to duplication.
