### ISSUE TITLE
I'm having issues getting my Atlas Scientific pH sensor to be found for calibration

### ISSUE THREAD

**Issue by Boellis** [kizniche/Mycodo#968]
EZO usb carrier board with Atlas Scientific pH sensor

Steps to replicate:
add sensor in calibration dropdown
select 3 point calibration
begin calibration

python -m pylibftdi.examples.list_devices
Output:
FTDI:FT230X Basic UART:DT04KQXQ
FTDI:FT230X Basic UART:DT04KSEB

Here's the log from the error i get:
`Error (Full Traceback):

Traceback (most recent call last):
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask_restx/api.py", line 639, in error_router
    return original_handler(e)
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/pi/Mycodo/mycodo/mycodo_flask/routes_calibration.py", line 515, in setup_atlas_ph
    current_stage='temperature', next_stage=next_stage)
  File "/home/pi/Mycodo/mycodo/mycodo_flask/routes_calibration.py", line 705, in dual_commands_to_sensor
    atlas_command = AtlasScientificCommand(input_sel)
  File "/home/pi/Mycodo/mycodo/utils/atlas_calibration.py", line 45, in __init__
    self.atlas_device = setup_atlas_device(input_dev)
  File "/home/pi/Mycodo/mycodo/utils/atlas_calibration.py", line 14, in setup_atlas_device
    atlas_device.ftdi_location)
  File "/home/pi/Mycodo/mycodo/devices/atlas_scientific_ftdi.py", line 21, in __init__
    Device.__init__(self, mode='t', device_id=serial_device)
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/pylibftdi/device.py", line 190, in __init__
    self.open()
  File "/home/pi/Mycodo/env/lib/python3.7/site-packages/pylibftdi/device.py", line 247, in open
    raise FtdiError(msg)
pylibftdi._base.FtdiError: b'device not found' (-3)

No device matching the given specification could be found.
Is the device connected?

Try running the following command to see if the device is listed:

    python -m pylibftdi.examples.list_devices`

**Comment by Boellis** [comment]
I realize now that you can just manually calibrate the probe. You can close this.
